### ISSUE TITLE
Add a wiki: Viki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#100]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://spacestation.fandom.com
Link to destination (independent) wiki: https://vsix.dev/wiki/

**Comment by Adrthegamedev** [comment]
https://vvvvvv.fandom.com/ should also be redirected here; both discuss the same game and have very similar content

**Comment by KevinPayravi** [comment]
Added! Will be in the next update.

**Comment by KevinPayravi** [comment]
Now available in version `2.0.0`
