### ISSUE TITLE
Add a wiki: Friends at the Table sub-wikis

### ISSUE THREAD

**Issue by radareclipse** [KevinPayravi/indie-wiki-buddy#101]
The Friends at the Table wiki was originally scattered across several different Fandom wikis, roughly one per season of the show. They've all consolidated in the independent fatt.wiki. [Announcement post for reference.](https://twitter.com/imperialhare/status/1567647925399863297)

Links to origin wikis: 
- [thenewarchives.fandom.com](https://thenewarchives.fandom.com)
- [counterweight.fandom.com](https://counterweight.fandom.com)
- [twilightmirage.fandom.com](https://twilightmirage.fandom.com)
- [partizan.fandom.com](https://partizan.fandom.com)
- [sangfielle.fandom.com](https://sangfielle.fandom.com)
- [visit-bluff-city.fandom.com](https://visit-bluff-city.fandom.com)

Link to destination (independent) wiki: [fatt.wiki](https://fatt.wiki)

**Comment by KevinPayravi** [comment]
Oh wow! Thanks for the submission I think those should be good to add.

In the long-term, I think it would be nice for the extension to "bundle" Fandom multiple wikis on the same topic together for the sake of making toggling simpler and saving space in the UI. This would also be helpful when there are archived versions of wikis on Fandom (e.g. zelda-archive, fallout-archive).

**Comment by KevinPayravi** [comment]
Indie Wiki Buddy now supports "grouping" of wikis; all the FaTT sub-wikis have been added and will be in the next release. Thanks for the submission!

**Comment by KevinPayravi** [comment]
Now available in version `2.0.0`
