### ISSUE TITLE
Add a wiki: Deep Rock Galactic

### ISSUE THREAD

**Issue by ix0rai** [KevinPayravi/indie-wiki-buddy#102]
Link to origin wiki: https://deeprockgalactic.fandom.com/
Link to destination (independent) wiki: https://deeprockgalactic.wiki.gg/

**Comment by KevinPayravi** [comment]
I've updated the README with these details as well (the getindie.wiki website said it, but not the README).

**Comment by ix0rai** [comment]
thanks!
