### ISSUE TITLE
The add-on links to Google Forms

### ISSUE THREAD

**Issue by TheFrenchGhosty** [KevinPayravi/indie-wiki-buddy#109]
The "Submit a Wiki" button links to https://form.getindie.wiki/

This redirect to a Google Forms (without warning).

This implies that this is the only way to submit new wikis, while the reality is that there's other ways (I submitted 2 wikis through it before discovering the other ways).

Google being Google, it's preferable to avoid them.

Please make https://form.getindie.wiki/ a page that mention the different way to submit new wikis.

**Comment by KevinPayravi** [comment]
The "Submit a Wiki" link in the extension popup will link to https://getindie.wiki/#submit in the next update. Thanks for opening this issue!

**Comment by KevinPayravi** [comment]
Now available in version `2.0.0`
