### ISSUE TITLE
Add a wiki (?): OMORI Wiki

### ISSUE THREAD

**Issue by cloudrac3r** [KevinPayravi/indie-wiki-buddy#117]
Link to origin wiki: https://omori.fandom.com/wiki/OMORI_WIKI
Link to destination (independent) wiki: https://omori.wiki/Main_Page

Note that the independent wiki has about half the pages of the fandom.com one. I haven't read any of the articles (because I haven't played the game) so I can't judge whether one of the wikis has or doesn't have better topic coverage than the other.

It's your call whether you want to add it to indie wiki buddy.

**Comment by KevinPayravi** [comment]
Thanks for the submission! Going to decline for now. I went down some rabbit holes, and it looks like the indie wiki is unfortunately missing a lot of important content. I do like the unique layout though.
