### ISSUE TITLE
Add a wiki: Sonic Retro

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#120]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://sonic.fandom.com/
Link to destination (independent) wiki: https://info.sonicretro.org/

**Comment by KevinPayravi** [comment]
19,908 vs. 6,812 articles, will need to take a closer look at this one.

**Comment by PencilVoid** [comment]
I would avoid redirecting from Sonic News Network to Sonic Retro, or at least have it disabled by default. I frequent both sites and would say they are not comparable in the information they provide and the way they present it.

**Comment by KevinPayravi** [comment]
@PencilVoid Thanks for the feedback! I'll go ahead and close this.
