### ISSUE TITLE
Filter results from Brave Search

### ISSUE THREAD

**Issue by MartyMcStarfox** [KevinPayravi/indie-wiki-buddy#127]

**Comment by KevinPayravi** [comment]
Done! Starting in version `2.1.0`, Indie Wiki Buddy will now filter search results in Brave. This update is already available for Firefox; it should be available in the Chrome store in 1-2 days, pending review from the Chrome Store team.

<img width="400" alt="A screenshot of Brave search results, showing a result from Animal Crossing Fandom Wiki being hidden." src="https://user-images.githubusercontent.com/7636606/236120770-5b449d63-9a4f-4e49-b859-49cf2422c600.png">

**Comment by MartyMcStarfox** [comment]
Thanks :)
