### ISSUE TITLE
Update Wikidex entry

### ISSUE THREAD

**Issue by termitavee** [KevinPayravi/indie-wiki-buddy#130]
Link to origin wiki: https://pokemon.fandom.com/es/wiki/Pok%C3%A9mon_Wiki
Link to destination (independent) wiki: https://www.wikidex.net/wiki/WikiDex

I used the form but notice in the code that wikidex was already added, just had a look and notice that the fandom changed the url ( was wikidex.fandom.com, and it redirects from that to the new one listed above. If I have time later I'll try to create a OR with the changes.

Also, It may be interesting to have a template to change or update a wiki (like this case)

**Comment by KevinPayravi** [comment]
Thanks for the report! Indie Wiki Buddy was using `pokemon.fandom.com/es`, but was referring to the site as "WikiDex (Fandom)". This has been updated to "Pokémon Fandom Wiki" in https://github.com/KevinPayravi/indie-wiki-buddy/commit/a4d233489e87ebe6bba76689096f86fdeba67d28
