### ISSUE TITLE
Add a wiki: The Adventure Zone Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#135]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://theadventurezone.fandom.com/wiki/The_Adventure_Zone_Wiki
Link to destination (independent) wiki: https://adventurezonewiki.miraheze.org/wiki/The_Adventure_Zone_Wiki

**Comment by Elaeagnifolia** [comment]
Destination wiki has more content pages (780 vs. 1980) as well as appears to have much more active editing based on Special:RecentChanges.

**Comment by KevinPayravi** [comment]
Now available in version `2.2.0`
