### ISSUE TITLE
Add a wiki: Botworld Adventure Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#145]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://botworld-adventure.fandom.com/wiki/Botworld_Adventure_Wiki
Link to destination (independent) wiki: https://www.botworld.wiki/

**Comment by Elaeagnifolia** [comment]
Does not use traditional Wiki software. No easy way to generate redirect links.

**Comment by KevinPayravi** [comment]
Closing, not a wiki
