### ISSUE TITLE
Add a wiki: Severance Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#149]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://severance-series.fandom.com/wiki/Severance
Link to destination (independent) wiki: https://severance.wiki/

**Comment by Elaeagnifolia** [comment]
Just a note that this is on DokuWiki similar to Dicey Dungeons and German Animal Crossing Wiki.

At a brief glance, content looks equivalent and/or better compared to the Fandom Wiki.

**Comment by KevinPayravi** [comment]
Now available in version `2.2.0`
