### ISSUE TITLE
Add a wiki: Yugipedia

### ISSUE THREAD

**Issue by Dinoguy1000** [KevinPayravi/indie-wiki-buddy#15]
Link to origin wiki: https://yugioh.fandom.com
Link to destination (independent) wiki: https://yugipedia.com

**Comment by KevinPayravi** [comment]
Added with commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/6ce139388d9f4422a444c3be417b44db068275db! Thanks for submitting.
