### ISSUE TITLE
Add a wiki: TTSCPedia

### ISSUE THREAD

**Issue by PanchamBro** [KevinPayravi/indie-wiki-buddy#150]
Link to origin wiki: https://mssam.fandom.com/
Link to destination (independent) wiki: https://wiki.therofl98.co/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
It looks like there's a large content disparity between the source Wiki and destination Wiki (2,444 vs. 240 content pages). Some of the missing pages do appear to have content on them as well and aren't just empty pages.

**Comment by KevinPayravi** [comment]
Declining for now, redirection likely not useful with the large content gap.
