### ISSUE TITLE
Remove Miraheze wikis

### ISSUE THREAD

**Issue by lottieratworld** [KevinPayravi/indie-wiki-buddy#151]
[As Miraheze is officially shutting down, with winding-down operations starting on September 1st](https://meta.miraheze.org/wiki/Board/Policies/20230615-Statement), it might be wise to remove any wikis hosted on that wikifarm sometime before then so the extension doesnt redirect to a Miraheze shutdown notice instead of the information a user is looking for.
Until September maybe just disable/hide the redirects for now to give some time to see if any wikis move to independently hosted domains first? Or if the shutdown is canceled and operation of Miraheze is handed over to another team instead.

**Comment by KevinPayravi** [comment]
Really unfortunate situation :( It looks like there are ongoing discussions to save Miraheze, so we'll see how those go. I think we can consider removing the redirects closer to the shutdown date, or if things get even more unstable.

**Comment by Elaeagnifolia** [comment]
Per https://meta.miraheze.org/wiki/Miraheze_is_Not_Shutting_Down for the timebeing Miraheze isn't shutting down, so I think it's safe to close this issue.
