### ISSUE TITLE
Add a wiki: EvaGeeks

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#154]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://evangelion.fandom.com
Link to destination (independent) wiki: https://wiki.evageeks.org/

**Comment by KevinPayravi** [comment]
Origin has activity and 1,089 articles. Destination appears inactive and has 634 articles.

**Comment by KevinPayravi** [comment]
Note: PR is open for this https://github.com/KevinPayravi/indie-wiki-buddy/pull/91

**Comment by memmam** [comment]
> Origin has activity and 1,089 articles. Destination appears inactive and has 634 articles.

Note, destination is NOT inactive, and origin heavily plagiarizes destination.

**Comment by KevinPayravi** [comment]
@memmam Thanks for the feedback on the PR! It's hard to gauge wikis I'm not familiar with, so it's helpful to get feedback from their readers and editors.

By inactivity, I mean that the wiki hasn't had any edits in [at least the last 30 days](https://wiki.evageeks.org/Special:RecentChanges?limit=50&days=30&enhanced=1&urlversion=2), is running a MediaWiki version that reached end-of-life in November 2020, and seems to have stopped processing [new signup requests](https://forum.evageeks.org/thread/4512/Scribe-Sign-Up-Sheet/560/) in February.

If EvaWiki is still the go-to wiki and the Fandom wiki's activity is mostly playing catchup, then I'd be happy to add EvaWiki - but the wiki's lack of maintenance and not onboarding new editors will be a concern in the longer term.

**Comment by KevinPayravi** [comment]
Including in next release thanks to reader feedback

**Comment by KevinPayravi** [comment]
> Hey I'm just wondering about the status for this? Saw an Evangelion Fandom result on Google the other day and remembered.

Thanks for commenting - this totally fell off my radar, sorry about that. EvaWiki has been added in `v3.2.0` (now available on Chrome, and should be available on Firefox within a few days after review).
