### ISSUE TITLE
Filter results from Ecosia searches

### ISSUE THREAD

**Issue by Avakining** [KevinPayravi/indie-wiki-buddy#162]
Would it be possible to filter non-indie wiki results from Ecosia search results, in addition to the other search engines included?

**Comment by KevinPayravi** [comment]
Certainly! Will include this in the next update.

**Comment by dioxias** [comment]
would be interested in seeing this for Startpage as well

**Comment by KevinPayravi** [comment]
@dioxias will do! created a separate issue at https://github.com/KevinPayravi/indie-wiki-buddy/issues/163

**Comment by KevinPayravi** [comment]
Now available in version `2.3.0`! Already released for Firefox; may take a few days for Chrome as it is pending review by Google.

**Comment by KevinPayravi** [comment]
Just a note: Unfortunately, Ecosia is very sensitive to its results being replaced or modified. Their JavaScript code seems to expect the DOM to appear a very specific way, and modifying it causes their scripts to crash and causes issues like images not loading.

As a result, the Indie WIki Banner now appears at the very top above all the content (as opposed to the other search engines where it goes below the search bar and above the first result).

<img width="822" alt="A screenshot of an Ecosia search, showing the Indie Wiki Buddy notice banner at the very top" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/48038806-cf5f-49a6-b8d6-dc44e3fdc333">
