### ISSUE TITLE
Add a wiki: FamiWiki

### ISSUE THREAD

**Issue by PanchamBro** [KevinPayravi/indie-wiki-buddy#164]
Link to origin wiki: https://famicom.fandom.com/wiki/Famicom_Wiki
Link to destination (independent) wiki: https://famiwiki.net/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
Destination wiki has more content pages (600 vs. 44) and is more active than origin wiki.

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/d00a5bdaba2c10ef7a7768ab902b7a18e735b64b

**Comment by KevinPayravi** [comment]
Now available in version `2.3.0`
