### ISSUE TITLE
Add a wiki: Project Moon Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#167]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://library-of-ruina.fandom.com/wiki/Library_Of_Ruina_Wiki
Link to destination (independent) wiki: https://projectmoon.miraheze.org/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
The destination wiki is behind on edits (493 vs. 261), and a brief look shows pages that still appear to be a WIP (The pages literally have the text "WIP" under several sections) on the destination wiki that the origin wiki covers in detail.

**Comment by KevinPayravi** [comment]
Closing, at least for now, until the independent wiki has made more progress.

**Comment by KevinPayravi** [comment]
This wiki has been re-submitted, and it looks like the independent wiki now has 960+ articles (vs. ~580 on Fandom). Re-opening for review.
