### ISSUE TITLE
Add a wiki: Houkai Gakuen 2 Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#168]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://houkai2nd.fandom.com/
Link to destination (independent) wiki: https://houkai2nd.miraheze.org/

**Comment by Elaeagnifolia** [comment]
The Miraheze Wiki appears to be a near identical fork of the Fandom wiki. While the destination wiki does have slightly less content pages (4,912 vs. 4,670), it is much more actively edited than the origin wiki, with some pages having more up-to-date content than Fandom's pages.

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/a3bad646a1290bf73f30853f94dcc6fd3a976cbf

**Comment by KevinPayravi** [comment]
Now available in version `2.3.0`
