### ISSUE TITLE
Add a wiki: The Quake Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#169]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://quake.fandom.com/wiki/Quake_Wikia
Link to destination (independent) wiki: https://quakewiki.org/

**Comment by Elaeagnifolia** [comment]
There's a pretty large page disparity between the origin and destination wiki (2,693 vs. 479). In addition, the origin wiki shows much more recent activity.

Doing a quick skim, it seems the origin wiki covers more the Quake franchise while the destination wiki covers more of Quake a singular game in the series. There are pages on the Fandom wiki related to later Quake entries that do not exist on the destination wiki.
