### ISSUE TITLE
Add a wiki: Genfanad Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#170]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://genfanad.fandom.com/wiki/Genfanad_Wiki
Link to destination (independent) wiki: https://genfanad.info/

**Comment by Elaeagnifolia** [comment]
The Wikis are very similar to each other in layout, content and quantity of pages (1,769 vs. 1792). While both seem to have activity, the destination wiki does have more. A quick skim of a few pages does show that some content is more up-to-date than the origin wiki as well.

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/aaefcbd4688d252d5f5b7ae5e4285c95e85f6354

**Comment by KevinPayravi** [comment]
Now available in version `2.3.0`
