### ISSUE TITLE
Add a wiki: Dragon Age Origins Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#171]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://dragonage.fandom.com/wiki/Dragon_Age_Wiki 
Link to destination (independent) wiki: https://dragonage.neoseeker.com/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
There is a huge content gap between the origin and destination wiki (13,646 vs. 199 content pages). I don't see the benefit of a redirect here.
