### ISSUE TITLE
Add a wiki: Azur Lane Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#175]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://azur-lane.fandom.com/wiki/Azur_Lane_Wiki
Link to destination (independent) wiki: https://azurlane.koumakan.jp/wiki/Azur_Lane_Wiki

**Comment by Elaeagnifolia** [comment]
Destination Wiki is well ahead of the origin Wiki (204 vs. 3,322 content pages). Looks like a solid redirect candidate.

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/df4f26dbee1b97a4dcbb835e446d7a34c9baa93f

**Comment by KevinPayravi** [comment]
Found a second Azur Lane wiki on Fandom (`blhx.fandom.com`). I've added it to the extension alongside `azur-lane.fandom.com`.

**Comment by KevinPayravi** [comment]
Now available in version `2.3.0`
