### ISSUE TITLE
Add a wiki: Etrian Odyssey Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#181]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://etrian.fandom.com/wiki/Etrian_Odyssey_Wiki
Link to destination (independent) wiki: https://etrianodyssey.wiki/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
Destination wiki appears to be behind the origin wiki (1,457 vs, 146 content pages) with far fewer recent active edits.
