### ISSUE TITLE
Add a wiki: Hanna-Barbera Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#182]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://hanna-barbera.fandom.com/wiki/Hanna-Barbera_Wiki
Link to destination (independent) wiki: https://hanna-barberawiki.com/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
Destination wiki has more content pages over the origin wiki (5,341 vs. 8,012). Both wikis have recent activity, but the pages that I skimmed on the destination wiki did appear to look more high quality content-wise than the Fandom pages.

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/d38b64ca9c84e4edfcd228f38d2bdcc1a241f902

**Comment by KevinPayravi** [comment]
Now available in version `2.3.0`
