### ISSUE TITLE
Add a wiki: Spyro Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#183]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://spyro.fandom.com/wiki/Main_Page
Link to destination (independent) wiki: https://spyrowiki.com/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
Destination wiki appears to be behind the origin wiki (2,241 vs, 161 content pages) with not as much recent activity compared to the origin wiki.
