### ISSUE TITLE
Add a wiki: Crash Bandicoot Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#184]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://crashbandicoot.fandom.com/wiki/Bandipedia:Main_Page
Link to destination (independent) wiki: https://crashbandicootwiki.com/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
Destination wiki appears to be behind the origin wiki (1,358 vs. 246 content pages) with fewer recent active edits.
