### ISSUE TITLE
Add a wiki: Coasterpedia

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#185]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://rollercoaster.fandom.com/wiki/Roller_Coaster_Wiki
Link to destination (independent) wiki: https://coasterpedia.net/wiki/Coasterpedia_The_Roller_Coaster_Wiki

**Comment by Elaeagnifolia** [comment]
Destination wiki is well ahead of the origin wiki (1,924 vs. 14,018) and the pages I looked at went into greater content detail than the origin wiki.

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/39a0c6f2482660671fc6c1243bcdd3f48f099dc9

**Comment by KevinPayravi** [comment]
Now available in version `2.3.0`
