### ISSUE TITLE
Add a wiki: Disney Dreamlight Valley Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#189]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://disneydreamlightvalley.fandom.com/wiki/Disney_Dreamlight_Valley_Wiki
Link to destination (independent) wiki: https://dreamlightvalleywiki.com/Dreamlight_Valley_Wiki

**Comment by Elaeagnifolia** [comment]
The destination wiki is well ahead of the origin wiki (716 vs. 4,271 content pages) and page content/quality is more up-to-date.

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/b97038054167a3d18d891054494be237393c41e0

**Comment by KevinPayravi** [comment]
Now available in version `2.3.0`
