### ISSUE TITLE
Add a wiki: Touhou Wiki (Español)

### ISSUE THREAD

**Issue by ConnieJP** [KevinPayravi/indie-wiki-buddy#19]
Link to origin wiki: https://touhou.fandom.com/es/wiki/P%C3%A1gina_principal
Link to destination (independent) wiki: https://es.touhouwiki.net/wiki/Touhou_Wiki

I was going to suggest adding links to the other language Touhou Wikis, but it looks like there's only a Spanish fandom wiki. :)

**Comment by KevinPayravi** [comment]
This has been added and will be released in `v1.1.3` (which should be available on the extension stores within the next 48 hours). Thank you!
