### ISSUE TITLE
Add a wiki: Japari Library

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#190]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://kemono-friends.fandom.com/wiki/Japari_Library_Wiki
Link to destination (independent) wiki: https://japari-library.com/wiki/Main_Page

**Comment by Elaeagnifolia** [comment]
Destination wiki is well ahead of the origin wiki (472 vs. 5,917 content pages) with much higher recent activity.

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/9547415822363cd22a3abb2a24725509e7ce3aef

**Comment by KevinPayravi** [comment]
Now available in version `2.3.0`
