### ISSUE TITLE
Add a wiki: Mabinogi World Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#198]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://mabinogi.fandom.com/, https://mabinogipros.fandom.com/, https://mabipro.fandom.com/
Link to destination (independent) wiki: https://wiki.mabinogiworld.com/view/Wiki_Home

**Comment by Elaeagnifolia** [comment]
The destination Wiki is well ahead of the origin Wiki (460 vs. >30,000); however, I believe the only redirect should be from https://mabinogi.fandom.com/. The other two Wikis look like they were created for Mabinogi private servers with unofficial custom content, not official Mabinogi content, which the destination Wiki does not appear to cover.

**Comment by KevinPayravi** [comment]
Adding in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/83c54a421d316cc377a2fa1e93fb0ef69fbbe945

**Comment by KevinPayravi** [comment]
Now available in version `2.4.0`
