### ISSUE TITLE
Add a wiki: Rhythm Heaven Wiki

### ISSUE THREAD

**Issue by PanchamBro** [KevinPayravi/indie-wiki-buddy#202]
Link to origin wiki: https://rhythmheaven.fandom.com/
Link to destination (independent) wiki: https://rhwiki.net/

**Comment by KevinPayravi** [comment]
Adding in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/83c54a421d316cc377a2fa1e93fb0ef69fbbe945

**Comment by KevinPayravi** [comment]
Now available in version `2.4.0`
