### ISSUE TITLE
Add a wiki: Find Everything Wiki

### ISSUE THREAD

**Issue by jummy0** [KevinPayravi/indie-wiki-buddy#205]
Link to origin wiki: [https://find-everything-rbx.fandom.com/](https://find-everything-rbx.fandom.com/) 
Link to destination (independent) wiki: [https://findeverything.miraheze.org/](https://findeverything.miraheze.org/)

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/a6c9e8071556d5089cc0daf791aa0dbbe45501f8

**Comment by KevinPayravi** [comment]
Now available in version `2.4.4` (may take a few days to appear in the Chrome store)
