### ISSUE TITLE
Add a wiki: Pizza Tower Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#207]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://pizzatower.fandom.com/
Link to destination (independent) wiki: https://pizzatower.miraheze.org/wiki/Pizza_Tower_Wiki

Additional note from the submitter: "should note that the new Pizza Tower wiki is still in the process of moving from fandom but at least it won't be on fandom anymore"

**Comment by maromagimoro** [comment]
The migration process is finished and currently the editors continue to improve content and the wiki itself on Miraheze. FANDOM staff saw the migration occurrence and demoted admins with no intention to delete the wiki, of course. Old wiki is still getting raided by vandals and nothing is done by staff to improve the situation, the wiki doesn't have active admins anymore as well.

**Comment by KevinPayravi** [comment]
@maromagimoro thank you for the update! Will get this added in the next update.

**Comment by KevinPayravi** [comment]
Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/a6c9e8071556d5089cc0daf791aa0dbbe45501f8

**Comment by KevinPayravi** [comment]
Now available in version `2.4.4` (may take a few days to appear in the Chrome store)
