### ISSUE TITLE
Offer wiki redirects as a source for libredirect.

### ISSUE THREAD

**Issue by MrDowntempo** [KevinPayravi/indie-wiki-buddy#209]
I really like what this project acheives, by forwarding requests to fandom wikis, to better wikis before resorting to breezewiki. Before I discovered this extension, I was using libredirect to just use breezewiki. But libredirect is nice in that it also handles redirecting twitter to nitter and many other sites as well. In fact, IDEALLY, I'd prefer to JUST use libredirect since it would mean I could have one extension managing all my redirections. I would really love to see this curated list of wikis used as an address that libredirect could use for fandom redirections instead of JUST breezewiki. I prefer to have as few extensions installed as possible, so if this project could just be a data source for libredirect, that would be a better solution, in my eyes.

**Comment by KevinPayravi** [comment]
Hi @MrDowntempo - Indie Wiki Buddy's data is [here](https://github.com/KevinPayravi/indie-wiki-buddy/tree/main/data) and available for use. If you want LibRedirect to support redirecting to these wikis, then you'd need to talk to LibRedirect.

That being said, I'm not sure redirecting these individual wikis would be in the scope of LibRedirect. The wikis aren't alternative frontends, and while independent wikis will usually be more privacy-friendly than Fandom, many of these wikis still run tracking ads and analytical software.
