### ISSUE TITLE
Add a wiki: Loop Hero Wiki

### ISSUE THREAD

**Issue by despin** [KevinPayravi/indie-wiki-buddy#214]
Link to origin wiki: https://loophero.fandom.com/wiki
Link to destination (independent) wiki: https://antifandom.com/loophero/wiki

**Comment by KevinPayravi** [comment]
@despin Thanks for submitting a wiki. The link you provided (https://antifandom.com/loophero/wiki) isn't an independent wiki; antifandom.com is just an alternative frontend to view Fandom wikis without ads and bloat.
