### ISSUE TITLE
Add a wiki: Rhythm Heaven Wiki

### ISSUE THREAD

**Issue by GunBlazer** [KevinPayravi/indie-wiki-buddy#215]
Link to origin wiki: https://rhythmheaven.fandom.com/wiki/Home
Link to destination (independent) wiki: https://rhwiki.net/wiki/Home

**Comment by KevinPayravi** [comment]
Hi @GunBlazer - Rhythm Heaven Wiki is already in Indie Wiki Buddy as of version 2.4.0. If you're on 2.4.0+ and you're not seeing the Rhythm Heaven Wiki redirect, please let me know.
