### ISSUE TITLE
Add a wiki: lipu Wikipesija

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#22]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://tokipona.fandom.com/
Link to destination (independent) wiki: https://wikipesija.org/

**Comment by yunruse** [comment]
pona mute a!

I can attest that lipu Wikipesija is the better site here.

**Comment by KevinPayravi** [comment]
@yunruse thanks! Just to confirm, these are general reference wikis (like Wikipedia) that are written in Toki Pona, correct?

Do you know of any other wikis out there written in Toki Pona?

**Comment by yunruse** [comment]
@KevinPayravi Yep! This is effectively `tok.wikipedia.org`. It is the only _lipu sona_ (wiki) listed on the [language's website](https://tokipona.org); clearly there is the Fandom wiki, but to my knowledge there are no other major reference works beyond the two original books, the dictionary [_lipu Linku_](https://lipu-linku.github.io) and a whole host of various wonderful tutorials and guides

**Comment by KevinPayravi** [comment]
This has been added and will be released in `v1.3.0`
