### ISSUE TITLE
New Wiki: Mahjong Wiki

### ISSUE THREAD

**Issue by the7thNightmare** [KevinPayravi/indie-wiki-buddy#222]
Link to origin wiki: https://mahjong.fandom.com/wiki/Mahjong_Wiki

Link to destination (independent) wiki: https://riichi.wiki/Main_Page

Fandom: 46 pages

Independent: 350 pages

**Comment by KevinPayravi** [comment]
Thanks for the submission! I love that there is an independent wiki dedicated to mahjong. Will be included in the next release.

**Comment by KevinPayravi** [comment]
Now available in `v2.5.1`
