### ISSUE TITLE
Settings should have hyperlinks to mentioned wikis

### ISSUE THREAD

**Issue by spudpiggy** [KevinPayravi/indie-wiki-buddy#226]
it's just cool to see so many things in the list, it'd be nice if i could just click on a wiki and get sent to it if i just wanna check it out, Discovering wikis is a thing - closed issues for this made me discover that the viva pinata fandom is apparently active, pinataisland is very old and very inactive and i always wished there was a non-dead wiki for this series. (Sucks it's on fandom tho)

Anyway, there should be hyperlinks to the various wikis shown on the settings page, so that curious people can easily check them out.

**Comment by Elaeagnifolia** [comment]
Just a note that the Wiki icons on the Settings page do link to the destination Wikis, although the names of the destination Wikis themselves could definitely also have a link to make it more obvious.

**Comment by KevinPayravi** [comment]
Thanks for the idea @spudpiggy. Destination wikis are now links in `v2.5.0` (thanks @Elaeagnifolia for the PR).

<img width="574" alt="Screenshot 2023-09-20 at 9 25 47 AM" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/939aa84b-f65d-46db-94c0-c9a22f9ed082">
