### ISSUE TITLE
Add a wiki: Minecraft Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#228]
Minecraft Wiki will soon be forking. A release will be prepared for right when Minecraft Wiki forks, as they will be promoting this extension.

Link to origin wiki: https://minecraft.fandom.com
Link to destination (independent) wiki: https://minecraft.wiki

**Comment by MetalManiacMc** [comment]
The app does seem to be able to not block language wikis, but I don't know if it's an option while submitting the wiki so here's a reminder Fandom languages wikis shouldn't be blocked (yet?!).

**Comment by KevinPayravi** [comment]
> The app does seem to be able to not block language wikis, but I don't know if it's an option while submitting the wiki so here's a reminder Fandom languages wikis shouldn't be blocked (yet?!).

@MetalManiacMc Thanks for the reminder, and no worries - only the English Fandom Minecraft wiki will be redirected/filtered. There was previously a bug where all language versions of a Fandom wiki would be filtered from search engine results, but that has since been fixed.

**Comment by KevinPayravi** [comment]
Will be in `v2.5.1`, which goes live when MCW's fork goes live.

**Comment by spudpiggy** [comment]
new wiki just went live and 2.5.1 didn't just went live

**Comment by KevinPayravi** [comment]
@spudpiggy it's live now, you need to give me more than 30 seconds :P

**Comment by frozenpandaman** [comment]
Woohoo!
