### ISSUE TITLE
Add a wiki: ULTRAWIKI

### ISSUE THREAD

**Issue by PencilVoid** [KevinPayravi/indie-wiki-buddy#234]
Link to origin wiki: [ULTRAKILL Wiki on Fandom](https://ultrakill.fandom.com)
Link to destination (independent) wiki: [ULTRAWIKI ](https://ultrakill.miraheze.org)

ULTRAKILL Wiki on Fandom has 161 content pages. ULTRAWIKI on Miraheze has 90 content pages. Despite the discrepancy I would say they are roughly equal in information provided; ULTRAWIKI tends to merge related but unique subjects into one page where possible. Some articles on ULTRAWIKI regarding less prominent subjects are unfinished, however.

**Comment by KevinPayravi** [comment]
@PencilVoid Thanks for the submission! ULTRAWIKI is now available in `v2.5.2` (released on Firefox, and should be released on Chrome within the next day)
