### ISSUE TITLE
Add a wiki: Minecraft Wiki

### ISSUE THREAD

**Issue by NicoTheCinderace** [KevinPayravi/indie-wiki-buddy#238]
Link to origin wiki: https://minecraft.fandom.com/wiki/Minecraft_Wiki
Link to destination (independent) wiki: https://minecraft.wiki/

**Comment by NicoTheCinderace** [comment]
Since Minecraft moved it's wiki from fandom.com, I figured now would be the best opportunity to move it to the Indie Buddy Wiki!

**Comment by KevinPayravi** [comment]
Hi @NicoTheCinderace - thanks for the submission. Minecraft Wiki is already in IWB (see https://github.com/KevinPayravi/indie-wiki-buddy/issues/228). You should see it when you update the extension to v2.5.1.
