### ISSUE TITLE
Add a wiki: Minecraft wiki

### ISSUE THREAD

**Issue by Traehgniw** [KevinPayravi/indie-wiki-buddy#239]
Link to origin wiki: https://minecraft.fandom.com/wiki/Glow_Berries
Link to destination (independent) wiki: https://minecraft.wiki/

the move happened within the last 24 hours i think but it is a bit bigger than the old wiki already (the old wiki now has a WE HAVE MOVED popup)

**Comment by KevinPayravi** [comment]
Hi @Traehgniw - thanks for the submission. Minecraft Wiki is already in IWB (see https://github.com/KevinPayravi/indie-wiki-buddy/issues/228). You should see it when you update the extension to v2.5.1.
