### ISSUE TITLE
Add a wiki: minecraft.wiki

### ISSUE THREAD

**Issue by Koooper** [KevinPayravi/indie-wiki-buddy#240]
Link to origin wiki: https://minecraft.fandom.com/
Link to destination (independent) wiki: https://minecraft.wiki/

**Comment by KevinPayravi** [comment]
Hi @Koooper - thanks for the submission. Minecraft Wiki is already in IWB (see https://github.com/KevinPayravi/indie-wiki-buddy/issues/228). You should see it when you update the extension to v2.5.1.
