### ISSUE TITLE
Add a wiki: The Minecraft Wiki

### ISSUE THREAD

**Issue by GunBlazer** [KevinPayravi/indie-wiki-buddy#243]
Link to origin wiki: https://minecraft.fandom.com/wiki/Minecraft_Wiki
Link to destination (independent) wiki: https://minecraft.wiki/

**Comment by KevinPayravi** [comment]
Thanks for the submission. Minecraft Wiki is already in IWB (see https://github.com/KevinPayravi/indie-wiki-buddy/issues/228). You should see it when you update the extension to v2.5.1.
