### ISSUE TITLE
Add a wiki: BlazBlue Wiki

### ISSUE THREAD

**Issue by GunBlazer** [KevinPayravi/indie-wiki-buddy#244]
Link to origin wiki: https://blazblue.fandom.com/wiki/BlazBlue_Wiki
Link to destination (independent) wiki: https://blazblue.wiki/

**Comment by KevinPayravi** [comment]
Hi @GunBlazer - BlazBlue Wiki is already in Indie Wiki Buddy. Please let me know if it's not working for you.
