### ISSUE TITLE
Missing Minecraft Fandom Wiki

### ISSUE THREAD

**Issue by Enator18** [KevinPayravi/indie-wiki-buddy#247]
You guys are missing a minecraft fandom wiki called mcpc.fandom.com from your list of fandom wikis. It is now archived because apparently it merged with the main minecraft.fandom.com a while ago, but it still shows up in search results instead of the new minecraft.wiki.

EDIT: minecraft-archive.fandom.com is also missing from the list.

**Comment by KevinPayravi** [comment]
Thanks for the submission! Will get this added in the next release.

Note, minecraft-archive is already in Indie Wiki Buddy. Wikis that redirect to a single destination are grouped together under one option in the extension's settings (in this case, "Minecraft Fandom Wikis").

**Comment by azgoodaz** [comment]
Fandom controls minecraftwiki.net is there a way to redirect links from this website?

**Comment by KevinPayravi** [comment]
> Fandom controls minecraftwiki.net is there a way to redirect links from this website?

Since minecraftwiki.net just redirects to minecraft.fandom.wiki, Indie Wiki Buddy should be able to still catch and redirect it.
