### ISSUE TITLE
In Opera, Indie Wiki Buddy fails to redirect when clicking on search engine results

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#264]
An Opera user reported that when they do a Google search and click on a Fandom result, the redirect doesn't happen. After much head scratching, I found the issue:

By default, Opera will block extensions from running on search engines. This includes "hiding" when a user is navigating from a search engine to another site, which prevents IWB from doing the redirect. Search engine access can be enabled per-extension by going to `about:extensions` and selecting the "Allow access to search page results" option.

I don't think any action is needed here for IWB, I just wanted to file this issue as documentation and in case anyone else runs into it.

**Comment by Insane96** [comment]
This should be pinned (or have a message like the chromium bug one)

**Comment by KevinPayravi** [comment]
A note has been added for Opera users (similar to the Chrome bug one) in this commit: https://github.com/KevinPayravi/indie-wiki-buddy/commit/dd711f4a9a8056cd320fc96a29cbd662889e0e21

Will be included in next IWB release.
