### ISSUE TITLE
Add BreezeWiki options to set default theme (light, dark, system) and remove "try our affiliated extension" banner

### ISSUE THREAD

**Issue by CapoFantasma97** [KevinPayravi/indie-wiki-buddy#267]
There's no page to set a default theme, making many wikis stay in light mode and having to manually enable the dark theme for each page.

And there's always the banner on top advertising this addon despite already using it.

**Comment by KevinPayravi** [comment]
Hi @CapoFantasma97 - BreezeWiki is a separate product from Indie Wiki Buddy. You can file feature requests for BreezeWiki here: https://lists.sr.ht/~cadence/breezewiki-discuss
