### ISSUE TITLE
Add a wiki: Megami Tensei Wiki

### ISSUE THREAD

**Issue by Gautrot** [KevinPayravi/indie-wiki-buddy#273]
[Announced](https://twitter.com/MegaTenWiki/status/1719021351720321155) via their Twitter account.

Link to origin wiki: https://megamitensei.fandom.com/wiki/Megami_Tensei_Wiki
Link to destination (independent) wiki: https://megatenwiki.com/wiki/Main_Page

**Comment by Monoverde888** [comment]
fixed in #274

**Comment by Monoverde888** [comment]
it already released right? please close

**Comment by KevinPayravi** [comment]
Indeed, thanks!
