### ISSUE TITLE
Add a wiki: Cheese E Pedia

### ISSUE THREAD

**Issue by The64thGamer** [KevinPayravi/indie-wiki-buddy#276]
Link to origin wiki: https://chucke.fandom.com/wiki/Chuck_E._Cheese_Wiki
Link to destination (independent) wiki: https://cheeseepedia.org/

**Comment by KevinPayravi** [comment]
Not sure about this one. The Fandom wiki's scope is specifically Chuck E. Cheese, while Cheese-E-Pedia is "all things animatronics". A redirect could work if Cheese-E-Pedia covers Chuck E. Cheese is as much depth as the Fandom wiki does.

**Comment by The64thGamer** [comment]
The majority of the articles are of relation to Chuck E. Cheese. The wiki is open to contributions for other animatronic groups but about 90% of it is just CEC contributions, hence the name.

**Comment by KevinPayravi** [comment]
@The64thGamer Thanks! Will include in the next update.

**Comment by KevinPayravi** [comment]
Added in `v3.7.0` (now available for Chrome, release pending for Firefox).
