### ISSUE TITLE
Add a wiki: The Binding of Isaac: Epiphany Wiki

### ISSUE THREAD

**Issue by OpenSauce04** [KevinPayravi/indie-wiki-buddy#279]
Link to origin wiki: https://tboi-epiphany.fandom.com/
Link to destination (independent) wiki: https://tboiepiphany.wiki.gg/

**Comment by chocmake** [comment]
Yeah, seems to catch quite a few submissions. Perhaps the issue template could include some checkbox or comment that confirms the wiki isn't wiki.gg, or sticky a notice in the issues section.
