### ISSUE TITLE
Firefox Extension Page Suggestions

### ISSUE THREAD

**Issue by JinPlanter** [KevinPayravi/indie-wiki-buddy#282]
Just a heads up but you might want to add information to your firefox extension page that Indie Wiki Buddy is a FOSS extension under MIT as it'll probably help convince people to try it. 

Also in addition you might want to add your donation links to the same page👍

**Comment by KevinPayravi** [comment]
This is a very late response, but thank you for the suggestion! IWB's Firefox listing already includes the license and donation link in the sidebar.
