### ISSUE TITLE
Add a wiki: Rhythm Doctor

### ISSUE THREAD

**Issue by wolfplay013** [KevinPayravi/indie-wiki-buddy#285]
Link to origin wiki: https://rhythm-doctor.fandom.com/wiki/Rhythm_Doctor_Wiki
Link to destination (independent) wiki: https://wiki.rhythm.cafe/page/Main_Page

**Comment by chocmake** [comment]
Seems to be dupe of #213

**Comment by wolfplay013** [comment]
ah gotcha.
