### ISSUE TITLE
Russian fandom wikis are not redirecting to indie wikis

### ISSUE THREAD

**Issue by Denatle** [KevinPayravi/indie-wiki-buddy#288]
I.e. 
https://minecraft.fandom.com/ru/ - stays fandom
https://minecraft.fandom.com/en/ - redirects

**Comment by Denatle** [comment]
And if it is language dependent, can you add feature to redirect to eng wiki if russian alternative isn't available for now?

**Comment by KevinPayravi** [comment]
Hi @Denatle - it is language dependent, yes. We don't redirect non-English wikis to English wikis, with the assumption that someone looking for content in a specific language will want to stay in that language. I know some non-English Minecraft wikis may fork soon, which will be added to IWB once they do.

I'll make a separate issue for a feature to redirect to an English wiki when a native language wiki isn't available.

**Comment by KevinPayravi** [comment]
New issue created here: https://github.com/KevinPayravi/indie-wiki-buddy/issues/289
