### ISSUE TITLE
Add a wiki: Grand Theft Auto (GTA)

### ISSUE THREAD

**Issue by TenEXP** [KevinPayravi/indie-wiki-buddy#307]
Link to origin wiki: https://gta.fandom.com/wiki/Main_Page
Link to destination (independent) wiki: https://www.grandtheftwiki.com/Main_Page

**Comment by SRG27** [comment]
The GrandTheftWiki is [inactive](https://www.grandtheftwiki.com/index.php?title=Special:RecentChanges&days=365&from=&limit=500), outdated (lacks any of the newer [DLCs (Fandom URL)](https://gta.fandom.com/wiki/Updates_in_GTA_Online) or content included in them) and contains less information than the origin Fandom wiki.

**Comment by TenEXP** [comment]
Ah, I see. In light of that, I'll close the issue as not planned then.
