### ISSUE TITLE
Allow translation of the extension

### ISSUE THREAD

**Issue by Dinoguy1000** [KevinPayravi/indie-wiki-buddy#31]
It seems like an oversight to have the extension support non-English wikis, without providing for translations of the extension itself.

**Comment by fr0r** [comment]
+1, I would love to provide Brazilian Portuguese translations to this extension.

**Comment by MetalManiacMc** [comment]
I would be willing to help with the French translations.

**Comment by BabylonAS** [comment]
+100500. IWB now supports wikis in sixteen languages alongside English, so it's especially important. I'd gladly translate the extension to Russian.

I've closed the #515 issue I've opened, as I didn't notice this one existed.
