### ISSUE TITLE
Add a wiki: Shroud of the Avatar (SotAwiki)

### ISSUE THREAD

**Issue by Gamerhenky** [KevinPayravi/indie-wiki-buddy#316]
Link to origin wiki: https://shroudoftheavatar.fandom.com
Link to destination (independent) wiki: https://sotawiki.net

**Comment by KevinPayravi** [comment]
Closing, released in `v3.1.0`

**Comment by KevinPayravi** [comment]
@Gamerhenky thanks for the submission!
