### ISSUE TITLE
Add a wiki: Ultima Online (UOGuide)

### ISSUE THREAD

**Issue by Gamerhenky** [KevinPayravi/indie-wiki-buddy#317]
Link to origin wiki: https://ultimaonline.fandom.com
Link to destination (independent) wiki: https://www.uoguide.com

**Comment by chocmake** [comment]
The indie version has significantly more pages than the Fandom (7945 vs 314) and more content for every type of page I checked. Seems like a clear choice.

Sidenote: the indie home page hasn't apparently been updated to reflect newer game builds (it lists a 2017 build while the Fandom lists a 2021 build as the latest), however looking at the indie version's category page one can see it actually contains pages for more recent builds (eg: this [2022 version](https://www.uoguide.com/Publish_114)).

**Comment by KevinPayravi** [comment]
I'm not sure why this wasn't initially added (if there is a reason), but this has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
