### ISSUE TITLE
Add a wiki: THE FINALS Community Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#319]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://the-finals.fandom.com/wiki/THE_FINALS_Wiki
Link to destination (independent) wiki: https://www.thefinals.wiki/

**Comment by chocmake** [comment]
Indie version seems comparable, with the edge in number of pages and more types of content for certain entries (including a nice touch of some short HTML5 video clips showing gameplay of a device).

**Comment by KevinPayravi** [comment]
@chocmake thanks for reviewing the wikis, it's a big help!

Closing issue, released in `v3.1.0`
