### ISSUE TITLE
Always redirect the Main Page to the Main Page, regardless of page title

### ISSUE THREAD

**Issue by SnorlaxMonster** [KevinPayravi/indie-wiki-buddy#324]
Currently, Indie Wiki Buddy assumes that the page title will be the same for both the original and independent wiki. While this assumption is reasonable in most cases, it can fail for the main page, which many wikis choose to rename.

For example, on Yugipedia, the main page is named "Yugipedia", whereas on the Fandom wiki it is named "Yu-Gi-Oh! Wiki". A user recently [created a redirect](https://yugipedia.com/index.php?title=Yu-Gi-Oh!_Wiki&diff=prev&oldid=4926716) to try and resolve this issue.

**Comment by KevinPayravi** [comment]
Good call. Can probably best accomplish this by adding the main page as a property to our JSON data. I'll look into writing a script to automatically pull all main page titles.

**Comment by KevinPayravi** [comment]
Released in `v3.3.0`!
