### ISSUE TITLE
Add setting to disable showing changelog on update

### ISSUE THREAD

**Issue by mayankpatibandla** [KevinPayravi/indie-wiki-buddy#325]
Add an option to allow users to disable the changelog display upon each update. This customization will provide a more streamlined update experience for those who find the changelog less relevant to their usage.

**Comment by ColonelThirtyTwo** [comment]
I've had the changelog open up in the middle of me browsing, just because Firefox decided to update the addon. It's very disruptive.

**Comment by KevinPayravi** [comment]
Will have an opt-out option available in the next update. Thanks for the suggestion!

**Comment by KevinPayravi** [comment]
The next update (`v3.1.0`), which should be available in the next couple days, includes a toggle in the full settings page (open IWB popup and click on "View all settings" to access).

<img width="723" alt="Settings page" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/aca68442-e1f6-44f6-bfc9-85e1aaf6700d">

**Comment by BitGrub** [comment]
Disruptions should be opt-in in my opinion, not opt-out, but thanks for the update.

**Comment by KevinPayravi** [comment]
With `v3.2.0`, opening the changelog on-update is now opt-in, and it won't take over the active tab anymore. Sorry for any disruption this caused!
