### ISSUE TITLE
Add a wiki: Terraria

### ISSUE THREAD

**Issue by nrandle3** [KevinPayravi/indie-wiki-buddy#326]
Link to origin wiki: 

> https://fandom.com/terraria/wiki/Terraria_Wiki

Link to destination (independent) wiki: 

> https://terraria.wiki.gg/wiki/Terraria_Wiki

**Comment by ScrapBlox** [comment]
Wiki.gg is not considered Independent according to the website "While wiki.gg is a great platform, for the purposes of this extension, wiki.gg wikis are currently not considered independent and are out of this extension's scope. Fortunately, there is a Redirect to wiki.gg extension available for [Chrome](https://chrome.google.com/webstore/detail/redirect-to-wikigg/cngoemokfjekjkmajenlaokhnmmiinca) and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/redirect-to-wiki-gg/) that you can use alongside Indie Wiki Buddy."
