### ISSUE TITLE
Add a wiki: Toontown Rewritten Wiki

### ISSUE THREAD

**Issue by robertfwallis** [KevinPayravi/indie-wiki-buddy#329]
Link to origin wiki: https://toontownrewritten.fandom.com/
Link to destination (independent) wiki: https://toontownrewritten.wiki/

**Comment by robertfwallis** [comment]
Glad to hear it's in progress. Was just wondering - how does the extension work? Does it live-grab the new wikis added and cache them, or does the extension require an update for it to take effect?

**Comment by robertfwallis** [comment]
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/11021224/247a6e7c-0b6a-42d1-a5f8-4676af25642d)
Looks like the extension doesn't work too well with instances where I assume "subpages" are attached to the main result. These still link to the Fandom wiki.

**Comment by KevinPayravi** [comment]
@robertfwallis 

> Does it live-grab the new wikis added and cache them, or does the extension require an update for it to take effect?

At the moment, the extension requires an update for new wikis to take effect. I may look into having the extension fetch from an API in the future, as that would of course expedite how quickly wikis are added.

> Looks like the extension doesn't work too well with instances where I assume "subpages" are attached to the main result. 

Thanks for reporting this - Google results are unfortunately finicky and everchanging and I have to play catch-up. I'll get an update in to filter out those subpages again!

**Comment by KevinPayravi** [comment]
Closing, released in `v3.1.0`
