### ISSUE TITLE
Add a wiki: Sonic Wiki

### ISSUE THREAD

**Issue by AngrySonics** [KevinPayravi/indie-wiki-buddy#330]
Link to origin wiki: https://sonic.fandom.com/wiki/Sonic_Wiki_Zone
Link to destination (independent) wiki: https://info.sonicretro.org/

i mean, we have Sega Retro as an independent wiki of Sega Wiki, so why not have Sonic Retro as an independent wiki of Sonic Wiki Zone?

**Comment by Testsr** [comment]
#120 Already considered and rejected.

**Comment by AngrySonics** [comment]
oh. okay
