### ISSUE TITLE
Redirect to correct page on Minecraft Wiki

### ISSUE THREAD

**Issue by Ben524** [KevinPayravi/indie-wiki-buddy#334]
you can change minecraft fandom wiki URLs to minecraft wiki URLs,
to replace them you can replace `.fandom.com` in the URL to `.wiki`
becuase ot will auto redirect to the correct page on the new wiki.

**Comment by violine1101** [comment]
The extension should already work properly for the Minecraft Wiki, is there an issue for you where it doesn't redirect you properly?

**Comment by KevinPayravi** [comment]
Indeed, Minecraft Wiki is already in IWB. The newly-forked non-English Minecraft Wikis have also been added and will be available in the next update this week (see https://github.com/KevinPayravi/indie-wiki-buddy/pull/328 and https://github.com/KevinPayravi/indie-wiki-buddy/pull/337).
