### ISSUE TITLE
Add a wiki: Risk Of Rain Returns Wiki

### ISSUE THREAD

**Issue by NicoTheCinderace** [KevinPayravi/indie-wiki-buddy#335]
Link to origin wiki:  https://riskofrain.fandom.com/wiki/Risk_of_Rain_Returns
Link to destination (independent) wiki: https://riskofrainreturns.wiki.gg/wiki/Risk_of_Rain_Returns_Wiki

Here's an actual Wiki dedicated Risk Of Rain Returns itself - Since Hopoo Games themselves have actually migrated away from Fandom Wiki itself.

I figured that people who actually want to look up stuff for Risk Of Rain Returns should be able to do it on an officially endorsed Wiki by the devs themselves. I haven't seen any other suggestions like this pop up. I apologize if this doesn't quite fit the requirements, but I figured I'd try anyway!

**Comment by azgoodaz** [comment]
wiki.gg is supported through this add-on: https://github.com/freedomgamesdev/wikigg-redirect-extension

Nothing wrong in having both add-ons enabled.

**Comment by KevinPayravi** [comment]
Since we're starting to wiki.gg wikis, this can now be re-visited.

It looks like there's a bit of scope difference here. The Fandom wiki covers all three games (RoR, RoR2, and RoR Returns), while the wiki.gg seems to only cover Returns. It sounds like a big enough content gap to be an issue, but happy to hear thoughts from people more familiar with the game and/or wikis.

**Comment by azgoodaz** [comment]
They won't be on Fandom anymore. https://www.reddit.com/r/riskofrain/comments/17yyzw1/wiki_update_fandom_is_no_more/

**Comment by KevinPayravi** [comment]
It looks like there is now riskofrain.wiki.gg and riskofrain2.wiki.gg in addition to riskofrainreturns.wiki.gg, so we can perform the redirects. The original proposal of redirecting riskofrain.fandom.com to riskofrainreturns.wiki.gg had scope issues that I expressed earlier.

That both riskofrain.wiki.gg and riskofrain2.wiki.gg cover Risk of Rain 2 is...kind of weird, but alas.

**Comment by KevinPayravi** [comment]
Added in `v3.4.0`, now available for both Chrome + Firefox.
