### ISSUE TITLE
Add a wiki: Kynseed Wiki

### ISSUE THREAD

**Issue by DCNick3** [KevinPayravi/indie-wiki-buddy#336]
Link to origin wiki: https://kynseed.fandom.com/wiki/
Link to destination (independent) wiki: https://wiki.kynseed.com/wiki/

The independent wiki is actually ran by the game developers it seems

**Comment by KevinPayravi** [comment]
Thanks for the submission! I believe this wasn't originally added due to a gap in coverage, but the official wiki seems to have expanded since. This has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
