### ISSUE TITLE
Please add the Edge download link to your offical website

### ISSUE THREAD

**Issue by Steven-Jim** [KevinPayravi/indie-wiki-buddy#338]
<img width="669" alt="image" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/102276349/b63775cc-c3a0-444d-a5c8-36e99c827308">
Please add a button for your edge plugin https://microsoftedge.microsoft.com/addons/detail/redirect-to-wikigg/oecpcjdcedociegkjmlcepigjaenkenj

**Comment by violine1101** [comment]
That's a different extension, I don't think indie wiki buddy is on the edge web store.

**Comment by KevinPayravi** [comment]
Indeed - IWB is not currently on the Edge store, primarily due to the lengthier review times, but I may add it in the future. Edge users can download Chrome extensions.

**Comment by Steven-Jim** [comment]
ohno
so that's why this extension I've downloaded doesn't support Minecraft Wiki which is the main reason I looked for IWB...
Hope you would add it soon, since Chinese users can't access the Google extension store directly
---- Replied Message ----
| From | Kevin ***@***.***> |
| Date | 11/12/2023 22:20 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [KevinPayravi/indie-wiki-buddy] Please add the Edge download link to your offical website (Issue #338) |

Indeed - IWB is not currently on the Edge store, primarily due to the lengthier review times, but I may add it in the future. Edge users can download Chrome extensions.
