### ISSUE TITLE
Add a wiki: CalamityMod (Calamity mod for Terraria)

### ISSUE THREAD

**Issue by lucasP243** [KevinPayravi/indie-wiki-buddy#340]
Link to origin wiki: https://calamitymod.fandom.com
Link to destination (independent) wiki: https://calamitymod.wiki.gg

**Comment by KevinPayravi** [comment]
wiki.gg wikis are currently not included in Indie Wiki Buddy. It's a great platform, but their wikis don't meet our definition of independent (no defined migration policy, shared domain, limited skin and extension options, owned by a VC-backed company, etc.). Fortunately, there is a "Redirect to wiki.gg" extension available for [Chrome](https://chrome.google.com/webstore/detail/redirect-to-wikigg/cngoemokfjekjkmajenlaokhnmmiinca) and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/redirect-to-wiki-gg/) that you can use alongside Indie Wiki Buddy.
