### ISSUE TITLE
Add a wiki: Deep Rock Galactic Wiki

### ISSUE THREAD

**Issue by Gamepro5** [KevinPayravi/indie-wiki-buddy#341]
Link to origin wiki: [https://deeprockgalactic.fandom.com/wiki/Deep_Rock_Galactic_Wiki](https://deeprockgalactic.fandom.com/wiki/Deep_Rock_Galactic_Wiki)
Link to destination (independent) wiki: [https://deeprockgalactic.wiki.gg/wiki/Deep_Rock_Galactic](https://deeprockgalactic.wiki.gg/wiki/Deep_Rock_Galactic)

**Comment by KevinPayravi** [comment]
wiki.gg wikis are currently not included in Indie Wiki Buddy. It's a great platform, but their wikis don't meet our definition of independent (no defined migration policy, shared domain, limited skin and extension options, owned by a VC-backed company, etc.). Fortunately, there is a "Redirect to wiki.gg" extension available for [Chrome](https://chrome.google.com/webstore/detail/redirect-to-wikigg/cngoemokfjekjkmajenlaokhnmmiinca) and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/redirect-to-wiki-gg/) that you can use alongside Indie Wiki Buddy.
