### ISSUE TITLE
[bug] the extension don't seen to work on firefox using ecosia

### ISSUE THREAD

**Issue by Vilianexe** [KevinPayravi/indie-wiki-buddy#342]
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/72302817/588b2f12-362f-41e1-8b9f-3630b1b23068)
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/72302817/01d7536f-aa8c-424a-91fe-0d01ecde2f8a)
i tried reloading the page(using both f5 and shitf+f5) and restarting the browser too, and it didn't seen to fix it

i'm using Firefox 119

**Comment by KevinPayravi** [comment]
The search engine settings (including "hide non-indie results") only apply to Fandom and Fextralife wikis in which an independent alternative is available. It does not filter all Fandom wikis from search results. I can update the labels to make that clear.

I have received requests to filter _all_ Fandom wikis from search results, so it's on my radar. It will probably be a separate settings option.

**Comment by Vilianexe** [comment]
> The search engine settings (including "hide non-indie results") only apply to Fandom and Fextralife wikis in which an independent alternative is available. It does not filter _all_ Fandom wikis from search results. I can update the labels to make that clear.

but, leagueoflegends has an independent alternative, no?, because the extension redirect me when i click the link
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/72302817/1136b30a-a4ca-434a-9465-e206e8175cc3)

**Comment by KevinPayravi** [comment]
@Vilianexe There's no independent alternative that I know of. What you see in your screenshot is BreezeWiki, an alternative frontend for Fandom (i.e. you are viewing the League of Legends Fandom wiki through breezewiki.com). Indie Wiki Buddy has an opt-in option that redirects Fandom wikis to BreezeWiki when an independent alternative isn't available.

**Comment by Vilianexe** [comment]
oh, that make sense, sorry for the trouble, and thanks for the extension and your hard work ❤️

**Comment by KevinPayravi** [comment]
@Vilianexe no worries at all! Thanks for the kind words.
