### ISSUE TITLE
German Minecraft Fandom site doesn't get filtered or redirected 

### ISSUE THREAD

**Issue by Undercoverdog** [KevinPayravi/indie-wiki-buddy#346]
When searching for "Minecraft wiki" while having the extension enabled, all fandom search results are getting filtered except one entry for the German site of Minecraft Fandom.

Also when visiting that Fandom site, it doesn't redirect you to the German page of minecraft.wiki.

 I use Librewolf 119.0.1-1
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/64562491/069b482f-55bb-4d6a-95c1-5dda0208b4ae)

**Comment by MetalManiacMc** [comment]
And I believe that is done.

**Comment by KevinPayravi** [comment]
Closing, released in `v3.1.0`
