### ISSUE TITLE
Support custom BreezeWiki instances

### ISSUE THREAD

**Issue by ggtylerr** [KevinPayravi/indie-wiki-buddy#349]
Currently, you're only able to select the public list of Breezewiki instances. This means if you're running a private / self-hosted instance or you prefer one not on that list (i.e. [mine](https://breeze.ggtyler.dev)), you're unable to use that instance in this addon.

**Comment by KevinPayravi** [comment]
@ggtylerr Thanks for the suggestion. There is actually an old issue on this (https://github.com/KevinPayravi/indie-wiki-buddy/issues/131) that I previously declined, but am now re-opening. I'll see what I can do! Please follow that issue if you'd like to keep up to date on it.

If you'd like to have your mirror listed in IWB, I'd also be happy to add it, just let me know.

**Comment by ggtylerr** [comment]
That'd be nice, but I'd also like custom instance support in case anyone wanted to use their own instance :)

**Comment by KevinPayravi** [comment]
Added in `v3.2.0`! Now available on Chrome, and should be available on Firefox within a few days after review.

See https://github.com/KevinPayravi/indie-wiki-buddy/issues/131 for more details.
