### ISSUE TITLE
Does not support cn.bing.com

### ISSUE THREAD

**Issue by Leo204-LKY** [KevinPayravi/indie-wiki-buddy#351]
Microsoft Bing has a Chinese version website cn.bing.com, but the Display Banner feature does not support this website.
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/57821066/0a538922-d94e-44b4-817d-50d9303d19df)
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/57821066/ed3f35ef-5342-4729-a339-4fe86905c544)

**Comment by KevinPayravi** [comment]
Thanks for reporting this! I'll see if I can get IWB working for cn.bing.com in the next update.

**Comment by KevinPayravi** [comment]
Indie Wiki Buddy should now work on cn.bing.com as of `v3.2.0`. Please let me know if you run into any issues. Thank you!

**Comment by Leo204-LKY** [comment]
Thanks, it works now
