### ISSUE TITLE
Add a wiki: Metal Gear Wiki

### ISSUE THREAD

**Issue by Gamerhenky** [KevinPayravi/indie-wiki-buddy#355]
Link to origin wiki: metalgear.fandom.com
Link to destination (independent) wiki: metalgear.wiki

**Comment by KevinPayravi** [comment]
The independent wiki unfortunately doesn't appear maintained. The wiki is missing a logo, there are broken templates everywhere, and there have been 3 edits in the last 30 days. Happy to re-visit this if the Metal Gear Wiki is cleaned up and maintained.
