### ISSUE TITLE
Wrong Language Link about Minecraft Wiki

### ISSUE THREAD

**Issue by Louis-Harsune** [KevinPayravi/indie-wiki-buddy#357]
The minecraft.fandom.com/zh is a Chinese Website, but the extension link it to the English site!!
The Chinese Minecraft Wiki now: zh.minecraft.wiki
The linked English Minecraft Wiki: minecraft.wiki
The Old Chinese Minecraft Wiki: minecraft.fandom.com/zh
I've been confirm that the "Redirect non-English Fandom/Fextralife wikis to independent English wikis when no same-language wiki exists" has been opened. 

(PS: I'm Chinese, is it any wrong spelling in this Issue?)

**Comment by KevinPayravi** [comment]
Hi @Louis-ZYH - could you let me know which browser you are using?

Indie Wiki Buddy does link to the Chinese Minecraft Wiki (zh.minecraft.wiki) as of version 3.1.0. Can you confirm that you are using at least version 3.1.0 or 3.1.1? You can check your version by opening the settings popup, clicking "View All Settings", and then looking at the top-right of the settings page.

Also, please confirm that you don't have another extension installed (such as [this one](https://chromewebstore.google.com/detail/better-new-minecraft-wiki/njkogdlaalmifcbmhhlngeipfpoonafi)) that will redirect you to the English Minecraft Wiki site.

If you are using the latest version of Indie Wiki Buddy and don't have any other redirect extensions installed, then there may be a bug and I will take a closer look.

**Comment by Louis-ZYH** [comment]
Hi @KevinPayravi - Thanks for your suggestion about this.
First, I used 3.1.0, then I try to use 3.1.1, but the bug doesn't fixed.
Next, I'm now using Microsoft Edge Ver 119.0.2151.72（Stable）.
Then, I didn't install the extension "Better New Minecraft Wiki" such like [this one that you said that](https://chromewebstore.google.com/detail/better-new-minecraft-wiki/njkogdlaalmifcbmhhlngeipfpoonafi)
So, I think it is really a bug, I hope you take a back soon.

**Comment by KevinPayravi** [comment]
Thanks @Louis-Harsune! One more thing - could you share a screenshot of your settings for the Chinese Minecraft Wiki in Indie Wiki Buddy?

Open up the full Indie Wiki Buddy settings and filter by "中文 (ZH)", it should look like this:
<img width="696" alt="Screenshot of Chinese Minecraft wiki settings in Indie Wiki Buddy" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/368233c1-df9c-420b-a538-845a02c337d6">

**Comment by Louis-Harsune** [comment]
Emmm……Hi! I checked the setting and choose the "Search experience" to the right side……
And…The bug fixed!!!!!]
So thanks for your suggestions for me!!!
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/115140320/e5fa637c-9717-4a3a-978b-a1d4e9293887)
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/115140320/fe70d658-4238-43d0-9c2d-c35e2360bee9)

**Comment by KevinPayravi** [comment]
Ah, great! Thanks for letting me know, glad it's working for you.
