### ISSUE TITLE
Add a wiki: Valheim Wiki

### ISSUE THREAD

**Issue by maixmi** [KevinPayravi/indie-wiki-buddy#358]
Link to origin wiki: https://valheim.fandom.com/wiki/Valheim_Wiki
Link to destination (independent) wiki: https://valheim-wiki.com/Main_Page

**Comment by chocmake** [comment]
Similar number of pages (origin: 903, indie: 881). Indie seems to [lack pages](https://valheim-wiki.com/Enemies) for all enemies besides one, while Fandom has a [complete](https://valheim.fandom.com/wiki/Category:Creatures) set.

Some pages are fairly comparable though (eg: this shield page [origin](https://valheim.fandom.com/wiki/Banded_shield) vs [indie](https://valheim-wiki.com/Banded_shield_(Item))).

About page is empty so can't tell much else about it.

**Comment by KevinPayravi** [comment]
Man, I love Valheim and would love to have an indie wiki included. Unfortunately the content gap is big - per [Special:Statistics](https://valheim-wiki.com/Special:Statistics), the indie wiki only has 550 articles and no edits in the last 30 days. The Fandom Wiki is also unfortunately the official one and linked from the official Valheim website. Have to decline for now.
