### ISSUE TITLE
Add a wiki: Wiki of Mana

### ISSUE THREAD

**Issue by RampantSpirit** [KevinPayravi/indie-wiki-buddy#359]
Link to origin wiki: https://mana.fandom.com/wiki/Wiki_of_Mana
Link to destination (independent) wiki: https://wikiofmana.com/

Origin wiki has 2367 articles and the independent one has 3663. I'm not familiar with the series myself though, so I'm unsure about the quality of either resource.

**Comment by KevinPayravi** [comment]
Thank you for the submission! Added in `v3.2.0` (now available on Chrome, and should be available on Firefox within a few days after review).
