### ISSUE TITLE
Add a wiki: Gigantic Wiki

### ISSUE THREAD

**Issue by theoneandonlyleggy** [KevinPayravi/indie-wiki-buddy#360]
Link to origin wiki: https://gigantic.fandom.com/
There's also archived Gamepedia wiki which still shows up in search (it always was outdated): https://gigantic-archive.fandom.com/
Link to destination (independent) wiki: https://gogigantic.wiki/

**Comment by KevinPayravi** [comment]
Thank you for the submission! Added in `v3.2.0` (now available on Chrome, and should be available on Firefox within a few days after review).
