### ISSUE TITLE
Add a wiki: UnReal World

### ISSUE THREAD

**Issue by JoannaFalkowska** [KevinPayravi/indie-wiki-buddy#361]
Link to origin wiki: https://unrealworld.fandom.com/
Link to destination (independent) wiki: https://www.unrealworld.fi/wiki/

(The independent one is the official wiki that's supported by the game's developer, linked on their page here: https://www.unrealworld.fi/urw_links.html)

**Comment by KevinPayravi** [comment]
Thank you for the submission! Added in `v3.2.0` (now available on Chrome, and should be available on Firefox within a few days after review).
