### ISSUE TITLE
Add a wiki: Lethal Company Wiki

### ISSUE THREAD

**Issue by someone1230** [KevinPayravi/indie-wiki-buddy#363]
Link to origin wiki: https://lethal-company.fandom.com/wiki/Lethal_Company_Wiki
Link to destination (independent) wiki: https://lethal.miraheze.org/wiki/Main_Page

**Comment by KevinPayravi** [comment]
Added in https://github.com/KevinPayravi/indie-wiki-buddy/pull/367 by @Werefawkes

**Comment by KevinPayravi** [comment]
Thank you for the submission! Added in `v3.2.0` (now available on Chrome, and should be available on Firefox within a few days after review).
