### ISSUE TITLE
White text on white background

### ISSUE THREAD

**Issue by Fabian42** [KevinPayravi/indie-wiki-buddy#368]
Just installed it and saw this:
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/10481506/7f470b38-83dd-4554-abb6-51cf51d438e8)
I do have "Dark reader" installed, but it can't work on extension config pages. Nothing else should modify the colours.

**Comment by KevinPayravi** [comment]
@Fabian42 Thanks for reporting this. Could you let me know what browser you're using?

IWB is likely conflicting with some setting, whether on your browser or OS (I know Firefox as a "Manage Colors" setting that would be worth checking, if you use Firefox).

In the next IWB update, I'll explicitly set the font color, which should hopefully fix this issue.

**Comment by Fabian42** [comment]
Firefox, yes. The option was not enabled, but when I do enable it, the background becomes black and the text is visible.

**Comment by KevinPayravi** [comment]
Text color is now set in the CSS, so hopefully this issue is resolved. If you still experience any issues, please re-open this ticket. Thank you!
