### ISSUE TITLE
Add a wiki: Prison Architect Wiki

### ISSUE THREAD

**Issue by Galactipod** [KevinPayravi/indie-wiki-buddy#371]
Link to origin wiki: https://prison-architect.fandom.com
Link to destination (independent) wiki: https://prisonarchitect.paradoxwikis.com/index.php/Deliveries

The destination wiki is hosted by the publisher of Prison Architect. While this means it technically isn't independent of the developers, it is independent of wiki giants, and the developer oversight is not controversial within the community as far as I know. Overall, this wiki is the highest-regarded one within the Prison Architect community, often providing more useful information than the Fandom wiki.

**Comment by azgoodaz** [comment]
Download: https://github.com/freedomgamesdev/wikigg-redirect-extension

**Comment by KevinPayravi** [comment]
Hi @Galactipod - thanks for the submission! Even if not independent, this should be fine. I'm planning for the next update to start bringing in wikis that aren't strictly independent (wiki.gg, Telepedia, etc.) and this can be a part of that.

**Comment by KevinPayravi** [comment]
Added in `v3.3.0`! Will also explore adding the other Paradox wikis.
