### ISSUE TITLE
Add a wiki: Don't Starve wiki

### ISSUE THREAD

**Issue by huoyan1231** [KevinPayravi/indie-wiki-buddy#372]
Link to origin wiki: https://dontstarve.fandom.com/wiki/Don%27t_Starve_Wiki
Link to destination (independent) wiki: https://dontstarve.wiki.gg/

**Comment by KevinPayravi** [comment]
We don't currently consider wiki.gg to be independent (owned by a venture capital-backed company, no custom domains, limited technical self-control, etc.). Wiki.gg has its [own extension](https://github.com/freedomgamesdev/wikigg-redirect-extension) you can use to redirect to their wikis.
