### ISSUE TITLE
Add a wiki: Guild of Archivists

### ISSUE THREAD

**Issue by mkacct** [KevinPayravi/indie-wiki-buddy#377]
Link to origin wiki: https://dni.fandom.com/
Link to destination (independent) wiki: https://archive.guildofarchivists.org/

Destination wiki has over twice as many pages, and much more in-depth lore information.

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.5.0`, now available on both Chrome and Firefox.
