### ISSUE TITLE
Add a wiki: Dogcraft

### ISSUE THREAD

**Issue by WiIIiam278** [KevinPayravi/indie-wiki-buddy#378]
Link to origin wiki: https://dogcraft.fandom.com/
Link to destination (independent) wiki: https://dogcraft.net/wiki

We forked/moved back in July 2019 - now with nearly 5x the pages/users. Niche, but I hope that's still welcome~. :)

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.5.0`, now available on both Chrome and Firefox.
