### ISSUE TITLE
Add search engine: Yandex

### ISSUE THREAD

**Issue by BabylonAS** [KevinPayravi/indie-wiki-buddy#380]
With inclusion of the first Russian-language wiki (the [Russian Minecraft Wiki](https://ru.minecraft.wiki/)) pending, I guess it's time to also add support for the Russian search engine called Yandex (https://yandex.ru/search/?text=minecraft+wiki; also has a shorter URL ya.ru), which effectively forms a duopoly with Google in Russia with domestic usage share being comparable for both.

**Comment by BabylonAS** [comment]
I guess I’ve figured out appropriate selectors for Yandex:

- Search result card itself: `li[data-cid]` or `li.serp_item`
- Search result link: `li[data-cid] a.organic__link[href*="fandom.com"]` (or similar when using `li.serp_item` and/or filtering Fextralife links). This would be the global selector for results to filter.
- All search cards are in the `ul#search-result` list. The removal notice could be placed above that list tag.

Also, from what I’ve heard Yandex (but not ya.ru) uses non-RU top level domains, a bit like Google, so Yandex must be filtered using `yandex.` (no WWW) and `ya.ru` substrings.

**Comment by KevinPayravi** [comment]
Released in `v3.6.0`
