### ISSUE TITLE
Seems to not catch Skyrim Fandom Wiki

### ISSUE THREAD

**Issue by dis-guisekaylee** [KevinPayravi/indie-wiki-buddy#381]
The extension filters out the Elder Scrolls fandom.com site just fine, but not the Skyrim Fandom site, which is skyrim.fandom.com. My search queries included "how to make dwarven metal ingot in skyrim" and "skyrim wiki" and each time the first result was the Fandom site.

The top of the DuckDuckGo search result page says, "Indie Wiki Buddy has filtered out results from Elder Scrolls Fandom Wiki. Look for results from Unofficial Elder Scrolls Page instead."

For context, UESP has info on all ES games including Skyrim.

**Comment by KevinPayravi** [comment]
Will have skyrim.fandom.com added in the next update - thanks!

**Comment by KevinPayravi** [comment]
Added in `v3.4.0`, now available for both Chrome + Firefox. Had to add some logic to account for redirecting to the specific namespace of a wiki (in this case, the Skyrim namespace of UESP).
