### ISSUE TITLE
Add a wiki: Xenharmonic Wiki

### ISSUE THREAD

**Issue by arseniiv** [KevinPayravi/indie-wiki-buddy#382]
Link to origin wiki: https://xenharmonic.fandom.com
Link to destination (independent) wiki: https://en.xen.wiki

I didn’t even know there was a Fandom wiki out there. Right now, the “official” wiki is usually at the top in Google but better be safe. Everyone in the microtonal~xenharmonic community uses the latter one. It should be the one since migration from Wikispaces, I have no clue why there is a Fandom one.

Thank you very much for the work you do! 👏

**Comment by KevinPayravi** [comment]
Added in `v3.3.0`. Thanks for the submission!
