### ISSUE TITLE
Add a wiki: Deep Rock Galactic

### ISSUE THREAD

**Issue by BookSerpent** [KevinPayravi/indie-wiki-buddy#387]
Link to origin wiki: https://deeprockgalactic.fandom.com/wiki/Deep_Rock_Galactic_Wiki
Link to destination (independent) wiki: https://deeprockgalactic.wiki.gg/wiki/Deep_Rock_Galactic_Wiki

This is a wiki.gg wiki, but I believe it was announced that those are now allowed to be added to this extension.

**Comment by KevinPayravi** [comment]
Added in `v3.3.0`. Thanks for the submission!
