### ISSUE TITLE
Add a wiki: Brickipedia (LEGO Wiki)

### ISSUE THREAD

**Issue by ConnieJP** [KevinPayravi/indie-wiki-buddy#39]
Link to origin wiki: https://brickipedia.fandom.com/wiki/LEGO_Wiki
Link to destination (independent) wiki: https://en.brickimedia.org/wiki/Main_Page

**Comment by KevinPayravi** [comment]
Thanks for the submission!

I'm hesitant to add this one -- Brickimedia seems to have minimal activity and has fallen behind on staying up-to-date. As a LEGO fan, I see a lot of sets missing :(

I'm also not keen on including ShoutWiki wikis. They are friendly and allow for wikis to migrate off the platform, but they're a company, running an obsolete version of MediaWiki, are ad-heavy, and have limited extension support.
