### ISSUE TITLE
Add a wiki: Pathologic Wiki

### ISSUE THREAD

**Issue by isatsam** [KevinPayravi/indie-wiki-buddy#390]
Link to origin wiki: https://pathologic.fandom.com/wiki/Pathologic_Wiki
Link to destination (independent) wiki: https://pathologic.wiki.gg/wiki/Pathologic_Wiki
The Pathologic Wiki has recently moved away from Fandom. I'm not sure if it was announced anywhere except for their [Discord server](https://discord.gg/jswQ8Mx) ([link to the message](https://discord.com/channels/685147859662012531/685147860395884794/1162411198294274139)). Having a redirect to the new wiki would be really handy. Thank you!

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.5.0`, now available on both Chrome and Firefox.
