### ISSUE TITLE
[Website] Update wiki listing for 3.2.0, and correct header for Ukrainian language

### ISSUE THREAD

**Issue by AlsoScratch** [KevinPayravi/indie-wiki-buddy#396]
- [ ] Update to 3.2.0
- [ ] Correct local name for Ukrainian `Українська`
- [ ] Move Chinese to the end based on ISO code of `zh`

**Comment by KevinPayravi** [comment]
Listings updated through `3.3.0`! https://getindie.wiki/listings/

Thanks for the language/ordering fixes.
