### ISSUE TITLE
Add a wiki: TERRARIA

### ISSUE THREAD

**Issue by IsmaHdez** [KevinPayravi/indie-wiki-buddy#397]
Link to origin wiki: https://terraria.fandom.com/wiki/Terraria_Wiki
Link to destination (independent) wiki: https://terraria.wiki.gg/wiki/Terraria_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the request! We already have an open issue for Terraria (https://github.com/KevinPayravi/indie-wiki-buddy/issues/242) and it will be included in the next update.
