### ISSUE TITLE
Add a wiki: Guild Wars

### ISSUE THREAD

**Issue by kazerniel** [KevinPayravi/indie-wiki-buddy#402]
Link to origin wiki: https://guildwiki.fandom.com/wiki/Main_Page
Link to destination (independent) wiki: https://wiki.guildwars.com/wiki/Main_Page

The Fandom one has been dead for about a decade, but it still pops up prominently in some online searches. The destination is the official (and still actively edited) wiki hosted by the game's developers.

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.4.0`, will be available as soon as Chrome + Firefox approve the releases.
