### ISSUE TITLE
Add a wiki: WikiRaider

### ISSUE THREAD

**Issue by malfisya** [KevinPayravi/indie-wiki-buddy#403]
Link to origin wiki: https://tombraider.fandom.com/wiki/Tomb_Raider_Wiki
Link to destination (independent) wiki: https://www.wikiraider.com/index.php/Main_Page

**Comment by KevinPayravi** [comment]
Thanks for the submission!

Noting that there is also a German WikiRaider that can be redirected to: https://wikiraider.de/index.php/Hauptseite

**Comment by KevinPayravi** [comment]
Added in `v3.5.0`, now available on both Chrome and Firefox.

**Comment by VicCoca** [comment]
Sorry for the necro but this wiki is incomplete and hasn't been updated properly since, at least, 2018, which is when Shadow of The Tomb Raider released. I'd consider removing this wiki from the list, since it's of lower quantity and quality than the Fandom equivalent, sadly.
