### ISSUE TITLE
Add a wiki: Dark and Darker Wiki

### ISSUE THREAD

**Issue by Collaidetf2** [KevinPayravi/indie-wiki-buddy#404]
Link to origin wiki: https://dark-and-darker.fandom.com/wiki/Dark_and_Darker_Wiki
Link to destination (independent) wiki: https://darkanddarker.wiki.spellsandguns.com/Dark_and_Darker_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.5.0`, now available on both Chrome and Firefox.
