### ISSUE TITLE
Add a wiki: Darkest Dungeon

### ISSUE THREAD

**Issue by Collaidetf2** [KevinPayravi/indie-wiki-buddy#405]
Link to origin wiki: https://darkestdungeon.fandom.com/wiki/Darkest_Dungeon_Wiki
Link to destination (independent) wiki: https://darkestdungeon.wiki.gg/wiki/Darkest_Dungeon_Wiki

The google form refused to let me paste this wiki for some reason. It said it was a "breezewiki", and just a way to view fandom wikis. I refuse to believe that's correct, because there's a reddit thread discussing the migration of the official wiki away from fandom and using wiki.gg instead. As you've stated in what qualifies as a wiki worth adding, you mentioned that wiki.gg is not fully independent but you still permit it due to being better than fandom wikis. 

Here's the quote:
"Large hosts such as Miraheze and Wiki.gg may be considered less independent, but are included as they are community-friendly hosts, provide decent levels of control, and are popular destinations for forking wikis." [Submit a Wiki - https://getindie.wiki/ - Viewed 2023-12-29 13:47 CET]

Here's the link to the reddit thread that discusses the migration: https://www.reddit.com/r/darkestdungeon/comments/16upk01/darkest_dungeon_and_darkest_dungeon_ii_wiki_moved/

**Comment by KevinPayravi** [comment]
Ah, sorry about the form - a validation on that input was just misconfigured. Should work now.

**Comment by KevinPayravi** [comment]
Added in `v3.4.0`, now available for both Chrome + Firefox. Thank you!
