### ISSUE TITLE
Add a wiki: Necromerger wiki

### ISSUE THREAD

**Issue by Exorcism0666** [KevinPayravi/indie-wiki-buddy#408]
Link to origin wiki: https://necromerger.fandom.com/wiki/NecroMerger_Wiki
Link to destination (independent) wiki: https://necromerger.wiki.gg/

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.4.0`, will be available as soon as Chrome + Firefox approve the releases.
