### ISSUE TITLE
Add a wiki: Galaxy Life Wiki

### ISSUE THREAD

**Issue by Exorcism0666** [KevinPayravi/indie-wiki-buddy#409]
Link to origin wiki: https://galaxylife.fandom.com/wiki/Galaxy_Life_Wiki
Link to destination (independent) wiki: https://galaxylife.wiki.gg/

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.4.0`, will be available as soon as Chrome + Firefox approve the releases.
