### ISSUE TITLE
Add a wiki: Book of Travels Wiki

### ISSUE THREAD

**Issue by Exorcism0666** [KevinPayravi/indie-wiki-buddy#410]
Link to origin wiki: https://bookoftravels.fandom.com/wiki/Book_of_Travels_Wiki
Link to destination (independent) wiki: https://bookoftravels.wiki.gg/wiki/Book_of_Travels_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.4.0`, now available for both Chrome + Firefox.
