### ISSUE TITLE
Add a wiki: astroneer.wiki.gg

### ISSUE THREAD

**Issue by Meistermagier** [KevinPayravi/indie-wiki-buddy#414]
Link to origin wiki: https://astroneer.fandom.com/wiki/Astroneer_Wiki
Link to destination (independent) wiki: https://astroneer.wiki.gg/wiki/Astroneer_Wiki

**Comment by KevinPayravi** [comment]
Thanks for opening this issue! This has been added in [https://github.com/KevinPayravi/indie-wiki-buddy/pull/422](PR 422) and will be included in the next release.

**Comment by KevinPayravi** [comment]
Added in `v3.4.0`, will be available as soon as Chrome + Firefox approve the releases.
