### ISSUE TITLE
Plus signs replaced by underscores in article titles

### ISSUE THREAD

**Issue by SnorlaxMonster** [KevinPayravi/indie-wiki-buddy#418]
When redirecting from a Fandom wiki article that includes a plus sign in its title, the target link replaces any plus signs with underscores. For example, [Rise of the Duelist +1 Bonus Pack](https://yugioh.fandom.com/wiki/Rise_of_the_Duelist_%2B1_Bonus_Pack) on Yu-Gi-Oh! Fandom Wiki redirects to [a search for "Rise of the Duelist _1 Bonus Pack"](https://yugipedia.com/index.php?search=Rise%20of%20the%20Duelist%20_1%20Bonus%20Pack) on Yugipedia.

This appears to be a consequence of a workaround for Fextralife wikis, which encode spaces as plus signs in URLs. However, it's worth noting that plus signs are legal characters in article titles on Fextralife wikis too. For example, [Hide Armour +2](https://baldursgate3.wiki.fextralife.com/Hide+Armour++2) is a page on the Fextralife Baldur's Gate 3 wiki; it should redirect to [Hide Armour +2](https://bg3.wiki/wiki/Hide_Armour_%2B2), but instead redirects to a [search for "Hide_Armour__2"](https://bg3.wiki/w/index.php?search=Hide_Armour__2).

I was able to find an instance of a plus sign at the end of a pagename on an Fextralife wiki ([Heart +](https://starfield.wiki.fextralife.com/Heart++)), which gives me the impression that Fextralife only converts the first of consecutive plus signs in URLs to spaces. (According to the independent Starfield wiki, the item is named [Heart+](https://starfieldwiki.net/wiki/Starfield:Heart%2B) without the space in the middle, so the space's presence on the Fextralife wiki may be due to technical limitations.)

**Comment by KevinPayravi** [comment]
Thanks for opening this issue!

I've pushed a commit for Fextra wikis that will only replace the first `+` in a substring of consecutive spaces. This resolves the examples given (minus the extra space in Heart+, but not much we can do there given it's a technical limitation on Fextra's side).

**Comment by SnorlaxMonster** [comment]
> minus the extra space in Heart+, but not much we can do there given it's a technical limitation on Fextra's side

I didn't mean to imply this was a limitation of Indie Wiki Buddy. It would be up to Starfield Wiki to create a redirect from `Starfield:Heart +` to `Starfield:Heart+` (if they think such a redirect is important).
