### ISSUE TITLE
Failure to redirect page titled ??? on search engine

### ISSUE THREAD

**Issue by SnorlaxMonster** [KevinPayravi/indie-wiki-buddy#419]
On DuckDuckGo, the Yu-Gi-Oh! Fandom Wiki page titled "???" appears as one of the [search results for "yugioh wiki"](https://duckduckgo.com/?q=yugioh+wiki). However, Indie Wiki Buddy seems to be unable to redirect this URL to a specific page, instead just directing users to Yugipedia's Main Page.
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/7100450/906d07d6-49e4-42c4-a92e-c44a7a098e32)

This issue does not occur [on the Fandom page itself](https://yugioh.fandom.com/wiki/%3F%3F%3F). The banner at the top of the page correctly links to a search page that lands on [the ??? page on Yugipedia](https://yugipedia.com/wiki/%3F%3F%3F).

**Comment by KevinPayravi** [comment]
Ahh, thanks for pointing this out. This was due to a poor attempt at removing query parameters from the URL. Pushed a fix, will be in the next release.
