### ISSUE TITLE
Main Page redirection includes destination_content_prefix

### ISSUE THREAD

**Issue by SnorlaxMonster** [KevinPayravi/indie-wiki-buddy#425]
When redirecting the Main Page to a wiki with a `destination_content_prefix`, the Main Page title is assumed to use the prefix, even though this isn't usually the case.

For example, the [Fextralife Starfield Wiki](https://starfield.wiki.fextralife.com/Starfield+Wiki)'s Main Page is redirected to [a search for "Starfield:Home"](https://starfieldwiki.net/w/index.php?search=Starfield:Home), instead of sending the user directly to the page titled "[Home](https://starfieldwiki.net/wiki/Home)".

**Comment by KevinPayravi** [comment]
Implemented!

There is one wiki we have (YumeWiki) that uses the destination_content_prefix for their main pages, but fortunately they've set their bare main page title to redirect to the proper namespaces, so no issues there.

**Comment by KevinPayravi** [comment]
Added in `v3.4.0`, now available for both Chrome + Firefox.
