### ISSUE TITLE
Add a wiki: Fextralife Elder Scrolls Legends Wiki and Elder Scrolls Online Wiki

### ISSUE THREAD

**Issue by SnorlaxMonster** [KevinPayravi/indie-wiki-buddy#426]
Link to origin wiki: https://elderscrollslegends.wiki.fextralife.com/Elder+Scrolls+Legends+Wiki
Link to destination (independent) wiki: https://en.uesp.net/wiki/Legends:Legends (in "Legends" namespace)

Link to origin wiki: https://elderscrollsonline.wiki.fextralife.com/Elder+Scrolls+Online+Wiki
Link to destination (independent) wiki: https://en.uesp.net/wiki/Online:Online (in "Online" namespace)

The [Unofficial Elder Scrolls Pages](https://en.uesp.net/wiki/Main_Page) is already included as a destination for [Fandom's The Elder Scrolls Wiki](https://elderscrolls.fandom.com/wiki/The_Elder_Scrolls_Wiki), but without a content namespace. UESP has separate namespaces for each game, so the two Fextralife wikis can safely be redirected to those two content namespaces via `destination_content_prefix` (if specifying `destination_content_prefix` per-source instead of per-destination is supported).

I am not proposing redirecting the [French Fextralife Elder Scrolls Online Wiki](https://elderscrollsonline-fr.wiki.fextralife.com/Elder+Scrolls+Online+-+fr+Wiki) to the [French UESP wiki](https://fr.uesp.net/wiki/Accueil), as that wiki appears to be [severely lacking Elder Scrolls Online content at present](https://fr.uesp.net/wiki/Special:AllPages?namespace=144). Potentially that could be set up as a cross-language-only redirect though (for people who allow wikis in other languages to be redirected to the English wiki).

**Comment by KevinPayravi** [comment]
`destination_content_prefix` is currently only supported on the destination, but I should be able to also get it working on the origins. In progress!

**Comment by KevinPayravi** [comment]
Added in https://github.com/KevinPayravi/indie-wiki-buddy/commit/a32d3c52f08cbebc41240b0673436d64328d30d7, will be in the next release
