### ISSUE TITLE
Add a wiki: HoloCure Wiki

### ISSUE THREAD

**Issue by SuperSamus** [KevinPayravi/indie-wiki-buddy#428]
Link to origin wiki: https://holocure.fandom.com/wiki/HoloCure_Wiki
Link to destination (independent) wiki: https://holocure.wiki.gg/wiki/HoloCure_Wiki

Announcement post: https://reddit.com/r/holocure/comments/18xdz5y/holocure_wiki_has_moved_to_holocurewikigg/

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.4.0`, now available for both Chrome + Firefox.
