### ISSUE TITLE
Incorrect redirects for Miraheze wikis

### ISSUE THREAD

**Issue by Umgak** [KevinPayravi/indie-wiki-buddy#432]
When redirecting from Fandom to Miraheze, it appears the following 'template' is used:
`[wiki title].miraheze.org/w/index.php?search=[search term]`
However, this template results in improper redirects, as the Miraheze search page is actually here:
`[wiki title].miraheze.org/wiki/Special:Search?search=[search term]`

This incorrect redirect results in all searches for these wikis being redirected to the main page.
Tested with the following wikis:
Adventure Zone
Akudama Drive
Critical Role
Crypt of the NecroDancer
Find Everything
Houkai Gakuen 2
HyperRogue
Lethal Company

I would have tested more, but I think the point is proven. This may have been caused by an update on Miraheze's side.

**Comment by KevinPayravi** [comment]
Oof, thanks for pointing this out. I've pushed a commit (https://github.com/KevinPayravi/indie-wiki-buddy/commit/3a103dc6fb344d5d1d2c87797d9b94ade5116f1b) to update the search paths for Miraheze wikis to `/wiki/Special:Search`.

Looks like their `index.php` entrypoint requires a `&title=Special%3ASearch` query param for the search to work, but I'd like to test the impact of using that parameter (namely load times) before adding it in.

**Comment by OfficialCRUGG** [comment]
When can we expect this to be released?

**Comment by KevinPayravi** [comment]
@OfficialCRUGG The fix is in `v3.4.0`, which is now available for Chrome and should be available for Firefox within a few days (pending review by the Firefox add-ons team).

**Comment by KevinPayravi** [comment]
`v3.4.0` is now available for both Chrome + Firefox.
