### ISSUE TITLE
[Issue] | Possible comprised links

### ISSUE THREAD

**Issue by azgoodaz** [KevinPayravi/indie-wiki-buddy#437]
Deadcells recently linked the wiki.gg Redirector link ( https://www.reddit.com/r/deadcells/comments/1978fp7/official_wiki_redirector/ ) and if you have both the IndieWiki extension installed with wiki.gg and it's linking to comprised websites.

- If wiki.gg extension is installed, no bad link.
- If IndieWiki extension is installed, no bad link.
- If both extensions are installed, bad link.

![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/10385818/1df266aa-e6f1-4801-9c21-e7616ede88b8)

**Comment by KevinPayravi** [comment]
Hi @azgoodaz - can you provide more details:
* What page you were visiting, or link were you clicking, when this happened?
* How are the extension configured? Set to redirect, show banners, etc.?

I'm unable to replicate this issue with all three extensions installed (IWB, wiki.gg, and uBlock). My understanding of uBlock is that you can get a warning like that when uBlock prevents a malicious ad or pop-up from loading, and I don't think that's related to either IWB or wiki.gg extensions.

**Comment by azgoodaz** [comment]
Found it when clicking on this link here, https://www.reddit.com/r/deadcells/comments/1978fp7/official_wiki_redirector/

Settings are pretty normal
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/10385818/2a71b76e-ab8e-423e-bd89-0379c42b1e55)

**Comment by azgoodaz** [comment]
At first I thought it was a chromium issue since Firefox didn't get this link. But when I turned off IndieWiki and refresh the website to click on the link again the website worked. Although after turning off and turning back on IndieWiki the link works flawlessly now.

Just giving you a heads up if anyone else has this issue

**Comment by KevinPayravi** [comment]
Got it, thanks. The issue you experienced has nothing to do with Indie Wiki Buddy. uBlock likely just detected a malicious advertisement on Reddit and prevented the page from loading. Indie Wiki Buddy doesn't have access to run on reddit.com, so there isn't anything it could do to influence your experience there.
