### ISSUE TITLE
Add a wiki: vaporwave.wiki

### ISSUE THREAD

**Issue by thekirbykid20067** [KevinPayravi/indie-wiki-buddy#438]
Link to origin wiki: https://vaporwave.fandom.com/wiki/Vaporwave_Wiki
Link to destination (independent) https://vaporwave.wiki/wiki/Main_Page

This wiki was already moved ages ago as can be seen by the Fandom wiki's background. The name of the wiki is "vaporwave.wiki", **not** "Vaporwave Wiki"

**Comment by KevinPayravi** [comment]
Thanks for the submission! As a vaporwave fan I'm real happy to see this wiki.

Added in `v3.4.0`, will be available as soon as Chrome + Firefox approve the releases.
