### ISSUE TITLE
Add a wiki: Lost Media Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#44]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://lostmediaarchive.fandom.com/wiki/Lost_Media_Archive
Link to destination (independent) wiki: https://www.lostmediawiki.com/Home

**Comment by KevinPayravi** [comment]
Big gap between the two sites (7,600+ articles vs. 2,400+ articles) -- and between the two wikis, each has its own set of archived media. Likely not productive to redirect, as readers will be searching for specific media that potentially one site or the other has.

**Comment by PretzelBubbleTea** [comment]
The indie Lost Media Wiki has fewer articles due to quality and notability control: https://forums.lostmediawiki.com/thread/11320/which-opinion-lmw-lma
