### ISSUE TITLE
Add a wiki: Toontown Corporate Clash Wiki

### ISSUE THREAD

**Issue by Ian-07** [KevinPayravi/indie-wiki-buddy#449]
Link to origin wiki: https://toontown-corporate-clash.fandom.com/wiki/Toontown_Corporate_Clash_Wiki
Link to destination (independent) wiki: https://corporateclash.wiki.gg/wiki/Toontown_Corporate_Clash_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.4.0`, now available for both Chrome + Firefox.
