### ISSUE TITLE
Add a wiki: Undertale Yellow Wiki

### ISSUE THREAD

**Issue by NicoTheCinderace** [KevinPayravi/indie-wiki-buddy#453]
Link to origin wiki: https://undertaleyellow.fandom.com/wiki/Undertale_Yellow_Wiki
Link to destination (independent) wiki: https://undertaleyellow.wiki.gg/wiki/Undertale_Yellow_Wiki

Moved to Wiki.gg from fandom.

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.4.0`, now available for both Chrome + Firefox.
