### ISSUE TITLE
Add a wiki: Hearthstone Wiki

### ISSUE THREAD

**Issue by Magikh42** [KevinPayravi/indie-wiki-buddy#457]
Link to origin wiki: https://hearthstone.fandom.com/wiki/Hearthstone_Wiki
Link to destination (independent) wiki: https://hearthstone.wiki.gg/wiki/Hearthstone_Wiki

Please add Hearthstone Wiki

Thanks !

**Comment by KevinPayravi** [comment]
Hi @Magikh42 - thanks for the submission! Hearthstone Wiki was just added in `v3.4.0`, which was released on Chrome today and will be released on Firefox as soon as the Firefox team reviews the update.
