### ISSUE TITLE
Add a wiki: Dying Light 

### ISSUE THREAD

**Issue by Arbiterz** [KevinPayravi/indie-wiki-buddy#459]
Link to origin wiki: https://dyinglight.fandom.com/wiki/Dying_Light_Wiki
Link to destination (independent) wiki: https://dyinglight.wiki.gg/wiki/Dying_Light_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.5.0`, now available on both Chrome and Firefox.
