### ISSUE TITLE
Add a wiki: Against the Storm Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#479]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://against-the-storm.fandom.com
Link to destination (independent) wiki: https://hoodedhorse.com/wiki/Against_the_Storm

**Comment by KevinPayravi** [comment]
I've generally been accepting wikis hosted by the publishers. While not technically independent, they're generally high-quality, have no ads, and are the go-to community resource.

That being said, the lack of a free license is a concern to me too (good eye on catching that!). The wiki is missing both the [general disclaimer](https://hoodedhorse.com/wiki/Against_the_Storm/Against_the_Storm_Official_Wiki:General_disclaimer) and [copyrights](https://hoodedhorse.com/wiki/Against_the_Storm/Against_the_Storm_Official_Wiki:Copyrights) pages that would otherwise usually detail these things.

**Comment by otobot1** [comment]
I'm playing this game right now and I've tried to use both wikis. The fandom one is of very poor quality and I think that a redirect would be worth it in this case despite the license concerns.

**Comment by SnorlaxMonster** [comment]
For future reference, it appears that Hooded Horse has now added a footer to all of their wikis specifying that they are licenced under CC BY-SA 4.0. ([From Wayback Machine](https://web.archive.org/web/20240601032726/https://hoodedhorse.com/wiki/Against_the_Storm/Against_the_Storm_Official_Wiki), it was added sometime before June 1.)
