### ISSUE TITLE
Add a wiki: ENA Wiki

### ISSUE THREAD

**Issue by mkacct** [KevinPayravi/indie-wiki-buddy#481]
Link to origin wiki: https://enajoelg.fandom.com/
Link to destination (independent) wiki: https://ena.wiki.gg/

Origin (fandom.com) wiki is officially deprecated. Destination (wiki.gg) wiki outright replaces it.

Source: https://enajoelg.fandom.com/f/p/4400000000000038366

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.5.0`, now available on both Chrome and Firefox.
