### ISSUE TITLE
Non-indie link in EXPLORE FURTHER section disables entire search result (Bing)

### ISSUE THREAD

**Issue by plighting-engineerd** [KevinPayravi/indie-wiki-buddy#482]
In Microsoft Edge, if a search result has a non-indie result in the EXPLORE FURTHER section below it, the entire search result is disabled _even if the result is not from a non-indie wiki._

This can be seen below where a search result for an unrelated website is disabled to to a Minecraft Fandom link displayed below it.

<img width="482" alt="image" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/108758003/ac6ededb-7779-4b7c-a61d-3a54ced0a539">

**Comment by KevinPayravi** [comment]
See related issue https://github.com/KevinPayravi/indie-wiki-buddy/issues/484 - fix will be available in the next update. Thanks for reporting this!

**Comment by KevinPayravi** [comment]
Fix released in `v3.5.0`, now available on both Chrome and Firefox.

**Comment by plighting-engineerd** [comment]
Ah, great, thanks!
