### ISSUE TITLE
Incorrect handling of highlights

### ISSUE THREAD

**Issue by plighting-engineerd** [KevinPayravi/indie-wiki-buddy#483]
If a link appears in search results that has highlighting (such as https://minecraft.fandom.com/wiki/Village_mechanics#:~:text=A%20village%20is%20defined%20through,population%2C%20and%20Iron%20Golem%20population.) two issues arise:
1. The entire link is shown, which makes the banner hard to read. In addition, this can make the banner not fit within the space around it.
2. The `%20`s noting spaces in the link are converted to underscores, making the highlight not work at all

To fix this, either:
* The highlight should be removed from the display text as well as the redirect link
* Or the highlight should be removed from the display text and spaces should not be converted

I would be inclined to go with the former as the text in the article may have changed on the indie wiki post-fork.

The issue can be seen in the image below, which is a screenshot of Google's generative AI summary (with an example of the text making the banner too big). 
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/108758003/3e34ae0e-da74-4509-aa4e-18a851387b43)

**Comment by KevinPayravi** [comment]
Good find. I think we can safely filter out everything after a #, since that's an invalid character in titles for both MediaWiki and DokuWiki.

**Comment by plighting-engineerd** [comment]
Sounds good, thanks

**Comment by KevinPayravi** [comment]
This has been fixed (article name is now taken from the URL [pathname](https://developer.mozilla.org/en-US/docs/Web/API/URL/pathname), instead of trying to extract it from the entire URL). Will be in the next IWB update, which I'm hoping to release this week.

**Comment by KevinPayravi** [comment]
Fixed included in `v3.5.0`, now available on both Chrome and Firefox. Thank you for reporting it!
