### ISSUE TITLE
Failure to replace links on Yahoo search engine

### ISSUE THREAD

**Issue by SnorlaxMonster** [KevinPayravi/indie-wiki-buddy#487]
For me, Yahoo search is redirected to au.search.yahoo.com. However, it seems that IWB is not able to function on that site, because it has a regional subdomain. I imagine many other regions also have their own Yahoo subdomains.

For example, [this search](https://au.search.yahoo.com/search?p=borreload+savage+dragon) does not modify the Fandom link that appears as the first result.
![image](https://github.com/KevinPayravi/indie-wiki-buddy/assets/7100450/efe98c3a-6baf-4a9e-a9df-d29b6eec9954)

**Comment by KevinPayravi** [comment]
Odd, it does work for me. IWB's manifest permission for Yahoo is `https://*.search.yahoo.com/*`, which is why it (should) work.

<img width="669" alt="IWB working in Yahoo Search" src="https://github.com/KevinPayravi/indie-wiki-buddy/assets/7636606/db3d5d01-6257-41b3-a238-c45053eef180">

**Comment by SnorlaxMonster** [comment]
I think the cause is actually related to the tracking URLs Yahoo uses. When I modified the URL on the search result to be the real https://yugioh.fandom.com link instead of the https://r.search.yahoo.com tracking URL, IWB activated and successfully replaced the search result.

**Comment by KevinPayravi** [comment]
@SnorlaxMonster I think I got a fix in. Fortunately, the original URL is embedded within that tracking link, so it can be extracted and decoded (commit: https://github.com/KevinPayravi/indie-wiki-buddy/commit/851b7167ac3dd796e6173d3d113e0b147c44a680).
