### ISSUE TITLE
Add a wiki: Apex Legends Wiki

### ISSUE THREAD

**Issue by SDCore** [KevinPayravi/indie-wiki-buddy#490]
Link to origin wiki: https://apexlegends.fandom.com/wiki/Apex_Legends_Wiki
Link to destination (independent) wiki: https://apexlegends.wiki.gg/wiki/Apex_Legends_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in `v3.5.0`, now available on both Chrome and Firefox.
