### ISSUE TITLE
Add a wiki: Backpack Hero

### ISSUE THREAD

**Issue by Magikh42** [KevinPayravi/indie-wiki-buddy#507]
Link to origin wiki: https://backpack-hero.fandom.com/wiki/Backpack_Hero_Wiki
Link to destination (independent) wiki: https://backpackhero.wiki.gg/wiki/Backpack_Hero_Wiki

**Comment by KevinPayravi** [comment]
Added in https://github.com/KevinPayravi/indie-wiki-buddy/commit/723b8957b26db9443a6eaf586fcd3534e665352e, will be in the next release. Thank you!

**Comment by KevinPayravi** [comment]
Released in `v3.6.0` (available for Chrome, and should be available for Firefox soon)
