### ISSUE TITLE
Add a wiki: Dicey Dungeons

### ISSUE THREAD

**Issue by Magikh42** [KevinPayravi/indie-wiki-buddy#508]
Link to origin wiki: https://diceydungeons.fandom.com/wiki/Dicey_Dungeons_Wiki
Link to destination (independent) wiki: https://wiki.diceydungeons.com

Note: The new wiki does not seems to be running MediaWiki so I don't know if it should be redirected to

**Comment by SnorlaxMonster** [comment]
Duplicate of #97
