### ISSUE TITLE
Add a wiki: Enter the Gungeon Wiki

### ISSUE THREAD

**Issue by Magikh42** [KevinPayravi/indie-wiki-buddy#509]
Link to origin wiki: https://enterthegungeon.fandom.com/wiki/Enter_the_Gungeon_Wiki
Link to destination (independent) wiki: https://enterthegungeon.wiki.gg/wiki/Enter_the_Gungeon_Wiki

**Comment by KevinPayravi** [comment]
Added in https://github.com/KevinPayravi/indie-wiki-buddy/commit/723b8957b26db9443a6eaf586fcd3534e665352e, will be in the next release. Thank you!

**Comment by ashemedai** [comment]
Also closes #474

**Comment by KevinPayravi** [comment]
Released in `v3.6.0` (available for Chrome, and should be available for Firefox soon)
