### ISSUE TITLE
Add a wiki: TowerFall

### ISSUE THREAD

**Issue by Magikh42** [KevinPayravi/indie-wiki-buddy#510]
Link to origin wiki: https://towerfall.fandom.com/wiki/TowerFall_Wiki
Link to destination (independent) wiki: https://towerfall.wiki.gg/wiki/Towers

Note: There is also http://towerfall.wikidot.com/ but it it less updated and lot of images are missing so I think the addon should redirect to the wiki.gg wiki

**Comment by KevinPayravi** [comment]
Released in `v3.6.0` (available for Chrome, and should be available for Firefox soon)
