### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by BabylonAS** [KevinPayravi/indie-wiki-buddy#515]
With seventeen languages supported for wikis and counting, it's pretty obvious that the extension needs its UI to be translatable. If and when IWB adds localization support, I'd gladly provide the Russian translation for it!

**Comment by SnorlaxMonster** [comment]
I think this is effectively a duplicate of #31 (the oldest open Issue).

**Comment by BabylonAS** [comment]
I didn't notice it, probably because I was looking for “localization” and “internationalization”, not “translation”.
