### ISSUE TITLE
Add a wiki: TARDIS (Doctor Who) Wiki

### ISSUE THREAD

**Issue by ayyLumao** [KevinPayravi/indie-wiki-buddy#518]
Link to origin wiki: https://tardis.wiki/wiki/Doctor_Who_Wiki
Link to destination (independent) wiki: https://tardis.wiki/wiki/Doctor_Who_Wiki

**Comment by KevinPayravi** [comment]
Duplicate of https://github.com/KevinPayravi/indie-wiki-buddy/issues/516, has been added and will be in the next release.
