### ISSUE TITLE
Add a wiki: EXA_PICO Wiki

### ISSUE THREAD

**Issue by qwertystop** [KevinPayravi/indie-wiki-buddy#577]
Link to origin wiki: https://artonelico.fandom.com/wiki/The_EXA_PICO_Universe_Wiki
Link to destination (independent) wiki: https://exapico.wiki.gg/wiki/The_EXA_PICO_Universe_Wiki

**Comment by KevinPayravi** [comment]
| Metric                      |   EXA_PICO Universe Fandom Wiki |   EXA_PICO Wiki |
|:----------------------------|--------------------------------:|----------------:|
| Content pages               |                            1825 |            1475 |
| Active users                |                               1 |               2 |
| Recent edits (last 30 days) |                               0 |             338 |

**Comment by KevinPayravi** [comment]
wiki.gg wiki has grown considerably and is now larger + more active than the Fandom. Ready to add!

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
