### ISSUE TITLE
Add a wiki: Wars Wiki (from Neoseeker)

### ISSUE THREAD

**Issue by SnorlaxMonster** [KevinPayravi/indie-wiki-buddy#579]
Link to origin wiki: https://advancewars.neoseeker.com/wiki/Main_Page
Link to destination (independent) wiki: https://warswiki.org/wiki/Main_Page

A redirect from the Advance Wars Fandom wiki was already added to the independent Wars Wiki, so this would just be an additional origin for the existing redirect.

When I submitted the PR #461 adding Neoseeker as a redirect source, I included all Neoseeker wikis that had existing independent wikis in IWB. However, the redirect from Fandom's Advance Wars Wiki to Wars Wiki was added after I initially submitted that PR, so it ended up being missed. (It's the only wiki that this currently applies to.)

**Comment by KevinPayravi** [comment]
Added in `v3.6.2`
