### ISSUE TITLE
Add a wiki: Titanfall Wiki

### ISSUE THREAD

**Issue by GeckoEidechse** [KevinPayravi/indie-wiki-buddy#580]
Link to origin wiki: https://titanfall.fandom.com/
Link to destination (independent) wiki: https://titanfall.wiki.gg/

**Comment by GeckoEidechse** [comment]
See also the following related reddit posts:
- https://redd.it/1aq9sni
- https://redd.it/1b1qlxl
- https://redd.it/1b4i27x

**Comment by KevinPayravi** [comment]
Thank you for the submission! Added in `v3.7.0` (now available for Chrome, release pending for Firefox).
