### ISSUE TITLE
ULTRAWIKI has moved

### ISSUE THREAD

**Issue by PencilVoid** [KevinPayravi/indie-wiki-buddy#582]
Old wiki: https://ultrakill.miraheze.org/
New wiki: https://ultrakill.wiki.gg/

**Comment by SaphireLattice** [comment]
Would be nice if the miraheze wiki had that announced somewhere. Otherwise this feels a bit unsourced. I assume there's more info on Discord, but joining a discord to confirm that feels like unnecessary extra step.
