### ISSUE TITLE
Add a wiki: Langrisser Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#606]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://langrisser.fandom.com
Link to destination (independent) wiki: https://wikigrisser-next.com

**Comment by Gamerhenky** [comment]
Wikigrisser is just in scope about Langrisser Mobile specifically, not covers the entire franchise. For some reason, Wikigrisser isn't runs on MediaWiki like usually would.

**Comment by KevinPayravi** [comment]
@Gamerhenky Thank you! I'll go ahead and close this.
