### ISSUE TITLE
Add a wiki: Hypixel Skyblock

### ISSUE THREAD

**Issue by Naeodyy** [KevinPayravi/indie-wiki-buddy#617]
Link to origin wiki: https://hypixel-skyblock.fandom.com/wiki/Hypixel_SkyBlock_Wiki
Link to destination (independent) wiki: https://wiki.hypixel.net/Main_Page

**Comment by KevinPayravi** [comment]
Please see https://github.com/KevinPayravi/indie-wiki-buddy/issues/296 for further discussion on this - Hypixel Skyblock Wiki hasn't been added as it does not allow the public to sign up and edit. Feedback and thoughts welcome on that issue.
