### ISSUE TITLE
Add a wiki: Guilty Gear Wiki

### ISSUE THREAD

**Issue by tstephenson888** [KevinPayravi/indie-wiki-buddy#627]
Link to origin wiki: https://guiltygear.fandom.com
Link to destination (independent) wiki: https://guiltygear.wiki.gg

This should fit better than the old Dustloop link from previous versions

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added with https://github.com/KevinPayravi/indie-wiki-buddy/pull/623, will be included in next release.

**Comment by KevinPayravi** [comment]
Added in `v3.7.0` (now available for Chrome, release pending for Firefox).
