### ISSUE TITLE
Add a wiki: Popira Wiki

### ISSUE THREAD

**Issue by RyutoSetsujin** [KevinPayravi/indie-wiki-buddy#629]
Link to origin wiki: https://popira.fandom.com/wiki/Popira
Link to destination (independent) wiki: https://popira20.com/wiki/index.php?title=Main_Page

**Comment by KevinPayravi** [comment]
Thanks for the submission! This has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
