### ISSUE TITLE
Add a wiki: Wynncraft

### ISSUE THREAD

**Issue by Keiffermonster** [KevinPayravi/indie-wiki-buddy#638]
Link to origin wiki: https://wynncraft.fandom.com/wiki/Wynncraft_Wiki 
Link to destination (independent) wiki: https://wynncraft.wiki.gg/wiki/Wynncraft_Wiki

This is a wiki for a Minecraft server that averages around 1000 - 1500 players. currently the fandom wiki is the top result in google and duck duck go.

**Comment by DrWhoFan13** [comment]
(¬_¬")
https://github.com/KevinPayravi/indie-wiki-buddy/pull/615
Already been added, just waiting for the next update to be included

**Comment by Keiffermonster** [comment]
sorry! i should have looked glad to see its coming. :D :heart:
