### ISSUE TITLE
Add a wiki: YumeWiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#64]
We have requests to redirect the suite of Yume Nikki Fandom wikis to https://yume.wiki/. yume.wiki separates games by URL path, which will require separate listings for each game.

* `yumenikki.fandom.com` -> `yume.wiki/yume/*`
* `yume2kki.fandom.com` -> `yume.wiki/2kki/*`
* `answeredprayers.fandom.com` -> `yume.wiki/prayers/*`
* `outotsuyume.fandom.com` -> `yume.wiki/unevendream/*`
* `braingirl.fandom.com` -> `yume.wiki/braingirl/*`
* `dotflow.fandom.com` -> `yume.wiki/flow/*`
* `cerasus.fandom.com` -> `yume.wiki/cerasus/*`

There is also a separate subdomain for the general Yume Nikki Fangames Wiki.
* `yumenikkifg.fandom.com` -> `ynfg.yume.wiki/*`

**Comment by KevinPayravi** [comment]
Yume Wiki is separated into "sub-wikis" by path:
* `yumenikki.fandom.com/wiki/*` -> `yume.wiki/yume/*`
* `yume2kki.fandom.com/wiki/*` -> `yume.wiki/2kki/*`
* `answeredprayers.fandom.com/wiki/*` -> `yume.wiki/prayers/*`
* `outotsuyume.fandom.com/wiki/*` -> `yume.wiki/unevendream/*`
* `braingirl.fandom.com/wiki/*` -> `yume.wiki/braingirl/*`

**Comment by KevinPayravi** [comment]
Was planning to add in `v1.3.0`, but ran into technical issues (the separate paths cause some difficulty when trying to hit the MediaWiki search endpoint + search in the right namespace). Will have to take a closer look.

**Comment by lumiscosity** [comment]
more wikis have been added to yume.wiki since this issue was started:

- `dotflow.fandom.com/wiki/*` -> `yume.wiki/flow/*`
- `cerasus.fandom.com/wiki/*` -> `yume.wiki/cerasus/*`
- `yumenikkifg.fandom.com/wiki/*` -> `ynfg.yume.wiki/*`

**Comment by KevinPayravi** [comment]
@lumiscosity thank you! I've updated the initial post. Will be working on getting these all added today.

**Comment by KevinPayravi** [comment]
Dug into this some more. Ideally, each of the Fandom wikis would redirect to its respective yume.wiki path e.g. `yume2kki.fandom.com` should go to `yume.wiki/2kki/*`. However, Indie Wiki Buddy works by redirecting the user to `Special:Search/<articleName>`, which will either redirect the user to the article if it exists, or send them to a populated search page so the user can find the most relevant articles. `Special:Search` is only accessible at `yume.wiki/Special:Search`.

For example, say the user hits `yumenikki.fandom.com/wiki/Puddle_World`. Ideally the extension would redirect the user to `yume.wiki/yume/Special:Search/Puddle_World`, which would then send the user to `yume.wiki/yume/Puddle_World`. This doesn't work however, and the user would need to be send to https://yume.wiki/Special:Search/Puddle_World instead. From here the user is still able to find and click on the article their working for, but it's one extra step than would be ideal.

**Comment by KevinPayravi** [comment]
Addendum: I'm considering adding the ability to define a "prefix" for each wiki, so that Indie Wiki Buddy can prepend namespace names to searches. For example, if Yume's prefix is `Yume Nikki:`, Indie Wiki Buddy would be able to redirect `yumenikki.fandom.com/wiki/Puddle_World` to `yume.wiki/Special:Search/Yume_Nikki:Puddle_World`, which would take the user straight to `yume.wiki/yume/Puddle_World`.

**Comment by KevinPayravi** [comment]
Yume Wiki wikis (along with supporting namespaces) have been added with this commit: https://github.com/KevinPayravi/indie-wiki-buddy/commit/77eb43987461b31778216751fd7cc98c4eab123f

Will be in the next release.

**Comment by KevinPayravi** [comment]
Now available in version `2.3.0`!
