### ISSUE TITLE
Add a wiki: Liquipedia's Dota 2 Wiki

### ISSUE THREAD

**Issue by up201306506** [KevinPayravi/indie-wiki-buddy#640]
Link to origin wiki: https://dota2.fandom.com/wiki/Dota_2_Wiki
Link to destination (independent) wiki:  https://liquipedia.net/dota2game/Main_Page

Migration by the team away from Wikia and into Liquipedia. Official statement: https://old.reddit.com/r/DotA2/comments/1c4kg1n/official_announcement_dota_2_wiki_has_moved_to_a/

While the independence angle can be argued, this does increase editorial and framework liberties, even on small stupid issues that impact the whole of the frontpage, as demonstrated by [this comment and reply](https://old.reddit.com/r/DotA2/comments/1c4kg1n/official_announcement_dota_2_wiki_has_moved_to_a/kzojupr/). Layouts have already been reworked to improve the presentation, for example, a proper side-by-side layout on spell descriptions and their specifics and interactions with tabs, pages are now much more condensed. This also increases the overall shared knowledge base between the game and esports sides of things and integrations were stated to be worked on to improve both ends. From a user perspective, this is with little subjectivity the new home of dota knowledge.

**Comment by KevinPayravi** [comment]
Thank you for the submission! Added in `v3.7.0` (now available for Chrome, release pending for Firefox).

**Comment by Qunas101** [comment]
It redirects to the wrong wiki.
https://liquipedia.net/dota2/Main_Page is a wiki for Dota 2 esports
https://liquipedia.net/dota2game/Main_Page is the actual game wiki that has moved from fandom

**Comment by Qunas101** [comment]
@KevinPayravi sorry, just to make sure you get notified

**Comment by KevinPayravi** [comment]
Thanks @Qunas101! This has already been fixed for `3.7.1`, which has been released for Chrome but is pending review for Firefox. Should hopefully be released for Firefox in the next couple days.
