### ISSUE TITLE
Add a wiki: Harvestella

### ISSUE THREAD

**Issue by NeverSm1le** [KevinPayravi/indie-wiki-buddy#649]
Link to origin wiki: https://harvestella.fandom.com/wiki/Harvestella_Wiki
Link to destination (independent) wiki: https://harvestella.miraheze.org/wiki/Main_Page

**Comment by KevinPayravi** [comment]
Thank you for the submission! Unfortunately there's too large of a content gap here - Fandom has 925 articles vs. 78 on the Miraheze wiki (many of which are stubs).
