### ISSUE TITLE
Update wiki redirect: ULTRAWIKI (ultrakill.wiki.gg)

### ISSUE THREAD

**Issue by EepyBerry** [KevinPayravi/indie-wiki-buddy#655]
Link to origin wiki: https://ultrakill.fandom.com/ + https://ultrakill.miraheze.org/
Link to destination (independent) wiki: https://ultrakill.wiki.gg
---
The ULTRAWIKI hosted at [ultrakill.miraheze.org](https://ultrakill.miraheze.org/) is now deprecated and obsolete. The new wiki hosted on [https://ultrakill.wiki.gg](https://ultrakill.wiki.gg) replaces it while also being endorsed by the developers.

**Comment by KevinPayravi** [comment]
Thanks for the submission! The ULTRAKILL link has been updated, just waiting for the Chrome + Firefox stores to approve the release (hopefully within the next few days).

At the moment, we don't currently redirect away from Miraheze wikis (adding a domain is a whole process). We might consider in the future if there are enough use cases.
