### ISSUE TITLE
Add a wiki: Ultrakill Wiki

### ISSUE THREAD

**Issue by HackMeMan** [KevinPayravi/indie-wiki-buddy#657]
Link to origin wiki: https://ultrakill.miraheze.org
Link to destination (independent) wiki: https://ultrakill.wiki.gg/

**Comment by KevinPayravi** [comment]
Thanks for the submission! The ULTRAKILL wiki.gg wiki has been added, just waiting for the Chrome + Firefox stores to approve the release (hopefully within the next few days).
