### ISSUE TITLE
Add a wiki: ULTRAWIKI

### ISSUE THREAD

**Issue by slushieeru** [KevinPayravi/indie-wiki-buddy#660]
Link to origin wiki: https://ultrakill.fandom.com
Link to destination (independent) wiki: https://ultrakill.wiki.gg

current wiki that is redirected to from fandom is https://ultrakill.miraheze.org/ which is discontinued. the official one is above.

**Comment by DrWhoFan13** [comment]
The 3.7 update already fixed that. If it still redirects from Ultrakill Fandom to Ultrakill Miraheze, then you're on Firefox, which hasn't gotten the update yet.

**Comment by KevinPayravi** [comment]
Thanks for the submission! As mentioned above, IWB has been updated, but Firefox is pending a release approval.
