### ISSUE TITLE
Add a wiki: Explain XKCD Wiki

### ISSUE THREAD

**Issue by 1bcb** [KevinPayravi/indie-wiki-buddy#661]
Link to origin wiki: https://xkcd.fandom.com/wiki/Xkcd_Wiki
Link to destination (independent) wiki: https://www.explainxkcd.com/wiki/index.php/Main_Page

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added with commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/5a1ac577dbd00d1b90611cf351327a67415bf3de, will be in the next update.

**Comment by KevinPayravi** [comment]
`v3.7.1` now available for Chrome, release pending for Firefox.
