### ISSUE TITLE
Add a wiki: Prime-Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#668]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://prime-numbers.fandom.com/wiki/Prime_Numbers_Wiki
Link to destination (independent) wiki: https://www.rieselprime.de/ziki/Main_Page

**Comment by ToxicPea** [comment]
I'm not sure a redirect works for this. The two wikis seem to be about different things.

The independent wiki appears to be mainly about prime finding projects and primes found with those projects, while the fandom wiki appears to be about mainly smaller prime numbers.
