### ISSUE TITLE
Add a wiki: Fear & Hunger Wiki

### ISSUE THREAD

**Issue by YakiAttaki** [KevinPayravi/indie-wiki-buddy#677]
Link to origin wiki: https://fearandhunger.fandom.com/wiki/%22Fear_and_Hunger:_the_Tormentpedia%22_Wiki
Link to destination (independent) wiki: https://fearandhunger.wiki.gg/wiki/%22Fear_and_Hunger:_the_Tormentpedia%22_Wiki
Indepedent wiki exists and is of better quality than fandom wiki. Content warning for NSFW and general gruesome imagery and themes.

**Comment by KevinPayravi** [comment]
Fear & Hunger was added to Indie Wiki Buddy in `v3.4.0` (released for Chrome on January 29, and Firefox on February 1). Please let me know if you're experiencing issues with the redirect.

**Comment by YakiAttaki** [comment]
oh, huh, mine's just not updated. my apologies.
