### ISSUE TITLE
Add a wiki: 100% Orange Juice

### ISSUE THREAD

**Issue by bobberlington** [KevinPayravi/indie-wiki-buddy#681]
Link to origin wiki: https://100orangejuice.fandom.com/wiki/100%25_Orange_Juice_Wiki
Link to destination (independent) wiki: https://orangejuice.wiki/wiki/100%25_Orange_Juice_Wiki

**Comment by KevinPayravi** [comment]
Thanks for submitting this wiki! Added in `v3.8.0`.
