### ISSUE TITLE
Remove Pathfinder Kingmaker and WotR Fextralife->pathfinderwiki redirects

### ISSUE THREAD

**Issue by nicemoreoften** [KevinPayravi/indie-wiki-buddy#690]
pathfinderkingmaker.wiki.fextralife.com and pathfinderwrathoftherighteous.wiki.fextralife.com are set to redirect to pathfinderwiki.com

However, the Fextralife wikis are for the video games Pathfinder: Kingmaker and Pathfinder: Wrath of the Righteous while pathfinderwiki is generally for setting lore.

While it's desirable to not use Fextralife, pathfinderwiki is definitely not a good source for information on gameplay for those games.

**Comment by DrWhoFan13** [comment]
As the guy who made the PR that included the Pathfinder Fextra Redirects, I've removed them from [my latest PR.](https://github.com/KevinPayravi/indie-wiki-buddy/pull/688) They'll be gone in the next update that includes it.

**Comment by KevinPayravi** [comment]
PR merged, removals will be in the next update. Thank you!

**Comment by KevinPayravi** [comment]
Released in `v3.8.0`
