### ISSUE TITLE
Remove a wiki: A Wiki of Ice and Fire

### ISSUE THREAD

**Issue by memmam** [KevinPayravi/indie-wiki-buddy#693]
Link to origin wiki: https://gameofthrones.fandom.com/wiki/Wiki_of_Westeros

Link to destination (independent) wiki: https://awoiaf.westeros.org/index.php/Main_Page

Reason: the Game of Thrones Fandom is for the HBO TV franchise, while the independent wiki is for the book series it is based on.

The link between https://iceandfire.fandom.com/wiki/A_Song_of_Ice_and_Fire_Wiki and the destination wiki should stay, as both are wikis for the book series.

**Comment by memmam** [comment]
Made a pull request for this, see above.

**Comment by KevinPayravi** [comment]
Released in `v3.8.0`, thank you!
