### ISSUE TITLE
Add a wiki: Pressure Wiki

### ISSUE THREAD

**Issue by ghost** [KevinPayravi/indie-wiki-buddy#707]
Link to origin wiki: https://pressure.fandom.com/wiki/Pressure_Wiki
Link to destination (independent) wiki: https://urbanshade.org/wiki/Pressure_Wiki

**Comment by someone1230** [comment]
Link to origin wiki: https://pressure-roblox.fandom.com/wiki/Pressure_Wiki
Link to destination (independent) wiki: https://urbanshade.org/wiki/Pressure_Wiki

**Comment by KevinPayravi** [comment]
Thanks for submitting this wiki! Added in `v3.9.0` (now available for Chrome, should be available in Firefox within a few days).
