### ISSUE TITLE
Add a wiki: Oxygen Not Included (Klei Entertainment)

### ISSUE THREAD

**Issue by The-Toblin** [KevinPayravi/indie-wiki-buddy#714]
Link to origin wiki: https://oxygennotincluded.fandom.com/
Link to destination (independent) wiki: https://oxygennotincluded.wiki.gg/

**Comment by DrWhoFan13** [comment]
This has [already been included](https://getindie.wiki/changelog/) in 3.8.0, just wait for Firefox to approve the update.
