### ISSUE TITLE
Add a wiki: Bemani & Sega Rhythm Games

### ISSUE THREAD

**Issue by Xinnoh** [KevinPayravi/indie-wiki-buddy#715]
Remywiki is already part of this filter for the BEMANI fandom, the fandoms for bemani's individual games should be added.

Link to origin wiki: 
https://beatmania.fandom.com/wiki/Beatmania_IIDX_(series)
https://dancedancerevolution.fandom.com/wiki/Dance_Dance_Revolution_(DDR)_Wiki
https://jubeat.fandom.com/wiki/Jubeat_Wiki

The Pop'n and SDVX fandoms should imo not be included because the fandoms have complete and well maintained character/lore databases, whereas remy is focused mostly on songs/playable content and has many incomplete character pages. (All music/gameplay related stuff is up to date)
https://soundvoltex.fandom.com/wiki/Sound_Voltex_Wiki
https://popnmusic.fandom.com/wiki/Home

Link to destination (independent) wiki: 
https://remywiki.com/Main_Page

SilentBlue is a sub-wiki hosted by remywiki, used for Sega rhythm games (Ongeki, Chunithm, Maimai)

Link to origin wiki: 
https://maimai-intl.fandom.com/wiki/Maimai_(International_Version)_Wiki
https://maimaieng.fandom.com/wiki/Maimai_International_Wiki
https://chunithm.fandom.com/wiki/Main_Page
https://ongeki.fandom.com/wiki/O.N.G.E.K.I._Wiki

Link to destination (independent) wiki: 
https://silentblue.remywiki.com/Main_Page

**Comment by KevinPayravi** [comment]
Thanks for submitting all these! Added in `v3.9.0` (now available for Chrome, should be available in Firefox within a few days).

Here are the JSONs that list all the redirects I've included for RemyWiki and SilentBlue. Let me know if I missed anything.
https://github.com/KevinPayravi/indie-wiki-buddy/blob/v3.9.0/data/sitesEN.json#L877
https://github.com/KevinPayravi/indie-wiki-buddy/blob/v3.9.0/data/sitesEN.json#L5757
