### ISSUE TITLE
Add a wiki: Redirect to stardewvalleywiki from stardewcommunitywiki

### ISSUE THREAD

**Issue by dragon3025** [KevinPayravi/indie-wiki-buddy#717]
Link to origin wiki: https://stardewcommunitywiki.com/Stardew_Valley_Wiki
Link to destination (independent) wiki: https://stardewvalleywiki.com/Stardew_Valley_Wiki

There's already a redirect to this wiki from Fandom, but sometimes this old outdated Wiki shows up for results. For example: stardewcommunitywiki shows the latest updated for PC is 1.5.4, while stardewvalleywiki shows it's 1.6

**Comment by KevinPayravi** [comment]
While a redirect may be useful here, it's not really in our scope to redirect this wiki. Adding a new origin domain name also requires requesting new extension permissions, which is quite disruptive to users just to support one additional redirect.

stardewcommunitywiki.com appears down for me. Not sure if it's permanent, but if it is, I imagine it'll fall off of search engine results in time.
