### ISSUE TITLE
Add a wiki: Galaxy on Fire Wiki

### ISSUE THREAD

**Issue by Snoucher** [KevinPayravi/indie-wiki-buddy#720]
Link to origin wiki: https://galaxyonfire.fandom.com/wiki/Galaxy_on_Fire_Wiki
Link to destination (independent) wiki: https://galaxyonfire.wiki.gg/wiki/Galaxy_on_Fire_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! This has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
