### ISSUE TITLE
Add a wiki: Official Animal Well Wiki

### ISSUE THREAD

**Issue by mkacct** [KevinPayravi/indie-wiki-buddy#722]
Link to origin wiki: https://animal-well.fandom.com
Link to destination (independent) wiki: https://animalwell.wiki.gg

The origin wiki contains almost no content and is seemingly self-vandalized with the intent of preventing people from using it in favor of the official wiki.

**Comment by KevinPayravi** [comment]
Thanks for submitting this wiki! Added in `v3.9.0` (now available for Chrome, should be available in Firefox within a few days).
