### ISSUE TITLE
Add a wiki: Summitpedia (from FANDOM AntonBlast Wiki)

### ISSUE THREAD

**Issue by TheGoomba98** [KevinPayravi/indie-wiki-buddy#724]
Link to origin wiki: https://antonblastpedia.fandom.com/
Link to destination (independent) wiki: https://antonball.miraheze.org/wiki/Summitpedia:Main_Page

Considering AntonBlast is releasing later this year, I thought I'd get this request out here now.

**Comment by KevinPayravi** [comment]
Thanks for submitting this wiki! Added in `v3.9.0` (now available for Chrome, should be available in Firefox within a few days).
