### ISSUE TITLE
Add a wiki: Poupedia

### ISSUE THREAD

**Issue by PretzelBubbleTea** [KevinPayravi/indie-wiki-buddy#726]
Link to origin wiki: [pou.fandom.com](https://pou.fandom.com/wiki/)
Link to destination (independent) wiki: [poupedia.com](https://poupedia.com/)

**Comment by KevinPayravi** [comment]
Thanks for submitting this wiki! Added in `v3.9.0` (now available for Chrome, should be available in Firefox within a few days).
