### ISSUE TITLE
Add a wiki: Summitpedia (again, this time from FANDOM Antonball Wiki)

### ISSUE THREAD

**Issue by TheGoomba98** [KevinPayravi/indie-wiki-buddy#734]
Link to origin wiki: https://antonball.fandom.com/
Link to destination (independent) wiki: https://antonball.miraheze.org/wiki/Summitpedia:Main_Page

Turns out there's ANOTHER Anton-related wiki on Fandom.

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/5a40af57274d54dde3cb759af0a15d77411a1c07, will be in next release.

**Comment by KevinPayravi** [comment]
This has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
