### ISSUE TITLE
Add a wiki: RLCraft

### ISSUE THREAD

**Issue by Crypticc12** [KevinPayravi/indie-wiki-buddy#742]
Link to origin wiki: [Fandom](https://rlcraft.fandom.com/wiki/RLCraft_Wiki)
Link to destination (independent) wiki: [Wiki.gg](https://rlcraft.wiki.gg/wiki/RLCraft_Wiki)

**Comment by KevinPayravi** [comment]
Thanks for submitting this wiki! Added in `v3.9.0` (now available for Chrome, should be available in Firefox within a few days).

**Comment by Crypticc12** [comment]
Glad I could help! Love your extension and I hope you continue to maintain it!
