### ISSUE TITLE
Add a wiki: Limbus Company Wiki

### ISSUE THREAD

**Issue by ImmortalZypther** [KevinPayravi/indie-wiki-buddy#745]
Link to origin wiki: https://limbuscompany.fandom.com/wiki/Limbus_Company_Wiki
Link to destination (independent) wiki: https://limbuscompany.wiki.gg/wiki/Limbus_Company_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! Added in `v3.9.0`.
