### ISSUE TITLE
Limbus Company Wiki

### ISSUE THREAD

**Issue by LckiKoin736** [KevinPayravi/indie-wiki-buddy#746]
Link to origin wiki: https://limbuscompany.fandom.com/wiki/Limbus_Company_Wiki
Link to destination (independent) wiki: https://limbuscompany.wiki.gg/wiki/Limbus_Company_Wiki

Worked on by the same folks who edited for the Fandom wiki. Also Limbus Company Fandom wiki is being massively vandalised as of right now

**Comment by KevinPayravi** [comment]
Thank you for the submission! Added in `v3.9.0`.
