### ISSUE TITLE
Add a wiki: Wynncraft

### ISSUE THREAD

**Issue by AncientYears** [KevinPayravi/indie-wiki-buddy#749]
Link to origin wiki: https://wynncraft.fandom.com/wiki/Wynncraft_Wiki
Link to destination (independent) wiki: https://wynncraft.wiki.gg

**Comment by DrWhoFan13** [comment]
That wiki was added back in version 3.7.0. Have you tried checking your settings?

**Comment by AncientYears** [comment]
> That wiki was added back in version 3.7.0. Have you tried checking your settings?

Oh yea mb for some reason firefox didn't wanna update the extension at all mb

**Comment by DrWhoFan13** [comment]
> Oh yea mb for some reason firefox didn't wanna update the extension at all

That's likely because you didn't give permission for some of the new features in that update.
