### ISSUE TITLE
Add a wiki: Gronkh-Wiki (about German Let's Plays)

### ISSUE THREAD

**Issue by LogicDeLuxe** [KevinPayravi/indie-wiki-buddy#751]
Link to origin wiki: https://gronkh.fandom.com/de/wiki/Gronkh_Wiki
Link to destination (independent) wiki: https://gronkh-wiki.de/wiki/Hauptseite

**Comment by KevinPayravi** [comment]
@LogicDeLuxe Thanks for the submission! Just to clarify - these wikis are about the Gronkh network of game streamers, correct?

**Comment by LogicDeLuxe** [comment]
It is indeed about those game streamers. Well known in Germany.
The fandom site mentions a creation date of 05.01.2024, so it's probably not the original wikia site as stated in the imprint of the independent site. Yet, I noticed search engines coming up with that fandom site lately, which barely has anything on it.

**Comment by KevinPayravi** [comment]
This has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
