### ISSUE TITLE
Add a wiki: Limbus company

### ISSUE THREAD

**Issue by foco21** [KevinPayravi/indie-wiki-buddy#764]
Link to origin wiki: https://limbuscompany.fandom.com/wiki/Limbus_Company_Wiki
Link to destination (independent) wiki: https://limbuscompany.wiki.gg/wiki/Limbus_Company_Wiki

**Comment by KevinPayravi** [comment]
Added in `v3.9.0` (now available for Chrome, should be available in Firefox within a few days)
