### ISSUE TITLE
Add a wiki: Hypixel Skyblock Wiki

### ISSUE THREAD

**Issue by Arden-Cho** [KevinPayravi/indie-wiki-buddy#768]
Link to origin wiki: https://hypixel-skyblock.fandom.com/
Link to destination (independent) wiki: https://wiki.hypixel.net/

**Comment by KevinPayravi** [comment]
Please see https://github.com/KevinPayravi/indie-wiki-buddy/issues/296 for further discussion on this - Hypixel Skyblock Wiki hasn't been added as it does not allow the public to sign up and edit. Feedback and thoughts welcome on that issue.
