### ISSUE TITLE
Add a wiki: Shin Wiki Evangelion FR

### ISSUE THREAD

**Issue by codl** [KevinPayravi/indie-wiki-buddy#769]
Link to origin wiki: https://evangelion.fandom.com/fr/wiki/
Link to destination (independent) wiki: https://shinwikievangelionfr.miraheze.org/wiki/

**Comment by KevinPayravi** [comment]
Thanks for the submission! This has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
