### ISSUE TITLE
Add a wiki: Evil Prince and the Puppet Wiki

### ISSUE THREAD

**Issue by Gamerhenky** [KevinPayravi/indie-wiki-buddy#771]
Link to origin wiki: https://evil-prince-and-the-puppet.fandom.com
Link to destination (independent) wiki: https://akuaya.miraheze.org

**Comment by KevinPayravi** [comment]
Thanks for the submission! This has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
