### ISSUE TITLE
Add a wiki: Voidscape Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#783]
Link to origin wiki: https://voidscape.fandom.com/wiki/Voidscape_Wiki
Link to destination (independent) wiki: https://voidscape.tamaized.com/index.php/Main_Page

**Comment by KevinPayravi** [comment]
Thanks for the submission! This has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
