### ISSUE TITLE
Bug: Extention no longer works on Opera

### ISSUE THREAD

**Issue by cmkomppa123** [KevinPayravi/indie-wiki-buddy#786]
As said the extention no longer funktions on both Opera browsers, as it no longer redirects

**Comment by KevinPayravi** [comment]
Hi @cmkomppa123 - I just tried Indie Wiki Buddy in Opera and it seems to work fine. Could you answer the following questions?

* What specific features of Indie Wiki Buddy aren't working as expected?
* When was the last time you noticed Indie Wiki Buddy working as expected?
* Could you share a screenshot of your Indie Wiki Buddy settings?

**Comment by Julmik647** [comment]
In Opera there is a setting that blocks extensions from accesing search engine sites. You may need to turn it on.

**Comment by Julmik647** [comment]
Solution: #264
