### ISSUE TITLE
Add a wiki: The Python Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#787]
Link to origin wiki: https://python.fandom.com/wiki/Main_Page
Link to destination (independent) wiki: https://wiki.python.org/moin/

**Comment by KevinPayravi** [comment]
Thanks for the submission! Added Python Wiki (+ support for the MoinMoin platform) in commit https://github.com/KevinPayravi/indie-wiki-buddy/commit/5cb05368ec70265590fba28cae78097491e93de5, will be in the next release.

**Comment by KevinPayravi** [comment]
Available in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
