### ISSUE TITLE
Add a wiki: Mappercraft Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#788]
Link to origin wiki: https://mappercraft.fandom.com/wiki/Mappercraft_Wiki
Link to destination (independent) wiki: https://mappercraft.miraheze.org/wiki/Mappercraft_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! This has been added in `v3.10.1` (now available for Chrome, should be released for Firefox soon)
