### ISSUE TITLE
Add a wiki: AliceSoft (Rance, Evenicle, and others) Miraheze Wiki

### ISSUE THREAD

**Issue by bayazidbh** [KevinPayravi/indie-wiki-buddy#795]
Link to origin wiki: https://alicesoft.fandom.com/
Link to destination (independent) wiki: https://alicesoft.miraheze.org/wiki/AliceSoft_Wiki:Main_Page

Criteria:

> 1. The wiki should be editable by the public (that's what makes a wiki a wiki!)

A cursory look seems to indicate it is editable

> 2. The destination wiki should be independent, meaning that decision-making and control of the wiki largely rests with the wiki's staff and volunteer editing community.
> 2.a. Factors include editorial independence, the editorbase's ability to request changes from their host, and any history of the host exerting decisions contrary to a wiki community's wishes.
> 2.b. Large hosts such as Miraheze and Wiki.gg may be considered less independent, but are included as they are community-friendly hosts, provide decent levels of control, and are popular destinations for forking wikis.

As far as I recall, the community from fandom/wikia migrated to this new site. There were some hiccup, but it seems to be relatively stable now. If there is a more independent wiki, please tell me, but this is the one that's the main fork as far as I recall (though I cannot find the wikia discussion about moving anymore).

> 3. The destination wiki should be of decent quality, ideally matching (or exceeding) the quality and size of the origin wiki. While we want to support all independent wikis, we also want extension users to be directed to wikis where they can find what they are looking for.

It is at least of equal content to the fandom wiki. All the weird extra material details from the old wiki is there. Some category links are still broken, but the detail pages are still there. Censorship are also minimal - it's there, just to preserve some decency, but not unnecessarily as much as the old fandom wiki.

> 4. Should be of general interest. Wikis about particularly niche subjects may be discluded.

The wiki is for the entire catalogue of AliceSoft media. AliceSoft is a particularly notable visual novel creator who made the Rance series which ran for 30 years (practically the JoJo's Bizarre Adventure of Visual Novel), and currently creates Evenicle, Beat, and other series/works that's slowly gaining more general acknowledgement internationally.

It's not mainstream, but at the very least they are as notable as many recent wikis added to the extension.

> 5. When there are multiple independent wikis on the same subject, we will usually point to the wiki that is most complete and prominent in the community.

I am not aware of a more notable indie wiki for AliceSoft. If there is, I don't mind redirection there - anything's better than Fandom/Wikia.

**Comment by KevinPayravi** [comment]
Thanks for the details submission! See older duplicate issue: https://github.com/KevinPayravi/indie-wiki-buddy/issues/752

We'll get it added once we get an 18+ tag integrated.

**Comment by bayazidbh** [comment]
Ah, sorry, and thanks for the heads up. Hope it gets implemented soon.
