### ISSUE TITLE
Add a wiki: English Merc Storia Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#799]
Link to origin wiki: https://merc-storia-english.fandom.com/wiki/Merc_Storia_English_Wiki
Link to destination (independent) wiki: https://mercstoria.miraheze.org/wiki/Merc_Storia_English_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
