### ISSUE TITLE
Add a wiki: Quake Wiki

### ISSUE THREAD

**Issue by yum13241** [KevinPayravi/indie-wiki-buddy#803]
Link to origin wiki: https://quake.fandom.com
Link to destination (independent) wiki: https://quakewiki.org

**Comment by KevinPayravi** [comment]
Thanks for the submission! Please see the previous issues for Quake Wiki: https://github.com/KevinPayravi/indie-wiki-buddy/issues/169 https://github.com/KevinPayravi/indie-wiki-buddy/issues/370

The reason Quake Wiki hasn't been added is that the Fandom wiki covers the entire series, while the independent wiki covers only the first game.

**Comment by yum13241** [comment]
Oh I never noticed lol. Maybe it could redirect if the search contains "quake 1", "netquake", or "quakeworld"?
