### ISSUE TITLE
Add a wiki: Super Snail Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#813]
Link to origin wiki: https://super-snail.fandom.com/wiki/Super_Snail_Wiki
Link to destination (independent) wiki: https://supersnail.wiki.gg/wiki/Super_Snail_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
