### ISSUE TITLE
Add a wiki:  Zeldapendium

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#814]
Link to origin wiki: https://zelda.fandom.com/de/wiki/Zeldapedia:Hauptseite
Link to destination (independent) wiki: https://www.zeldapendium.de/wiki/Zeldapendium:Hauptseite

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
