### ISSUE TITLE
Add a wiki: The binding of Isaac: Rebirth

### ISSUE THREAD

**Issue by Tenebrosful** [KevinPayravi/indie-wiki-buddy#816]
Link to origin wiki: https://bindingofisaacrebirth.fandom.com/wiki/Binding_of_Isaac:_Rebirth_Wiki
Link to destination (independent) wiki: https://bindingofisaacrebirth.wiki.gg/wiki/Binding_of_Isaac:_Rebirth_Wiki

Also for other language like
Link to origin wiki: https://bindingofisaacrebirth.fandom.com/fr/wiki/Binding_of_Isaac:_Rebirth_Wiki
Link to destination (independent) wiki: https://bindingofisaacrebirth.wiki.gg/fr/wiki/Binding_of_Isaac:_Rebirth_Wiki

**Comment by UnnoticedShadow** [comment]
Can confirm. Death to Fandom!

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
