### ISSUE TITLE
Add a wiki: Clockup Wiki

### ISSUE THREAD

**Issue by G-Utopia** [KevinPayravi/indie-wiki-buddy#82]
Link to origin wiki: https://clockup.fandom.com
Link to destination (independent) wiki: https://en.clockupwiki.org

**Comment by KevinPayravi** [comment]
Thank you for the submission, and sorry for the very long wait. I'm unfortunately going to decline adding this for now -- both wikis are quite niche, very small, and currently inactive. Several of the links from the main page are either broken or incomplete, which hinders navigation. If ClockUp wiki resumes activity and grows a bit (especially covering high-level content), I'd be happy to re-visit.
