### ISSUE TITLE
Add a wiki: SYNTHETIK Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#820]
Link to origin wiki: https://synthetik.fandom.com/wiki/SYNTHETIK_Wiki
Link to destination (independent) wiki: https://synthetikuniverse.wiki.gg/wiki/SYNTHETIK_Universe_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
