### ISSUE TITLE
Add a wiki: Undertale Yellow Wiki

### ISSUE THREAD

**Issue by drown3d** [KevinPayravi/indie-wiki-buddy#823]
Link to origin wiki: https://antifandom.com/undertaleyellow/wiki/Undertale_Yellow_Wiki
Link to destination (independent) wiki: https://undertaleyellow.wiki.gg/wiki/Undertale_Yellow_Wiki

**Comment by KevinPayravi** [comment]
Hi @drown3d - Undertale Yellow Wiki was added in `v3.4.0` back in late January. Please make sure IWB is up-to-date. If you're still not seeing the redirect for Undertale Yellow Wiki, please let me know!
