### ISSUE TITLE
Move indie wikis above removing links instead of shifting

### ISSUE THREAD

**Issue by seth-rah** [KevinPayravi/indie-wiki-buddy#824]
## Summary

In the case of the megaten wiki, it's not up to date yet to match the content of the fandom wiki.

In these cases I'd like to use the fandom link to get a redirection to an alternative, but it seems the move to top has some weird artifact with the megaten wiki where it replaces the link instead of just shifting the result to the top

Or is this what the hide part of the function does?

Is there a way to seperate the hide / shifting to top?

![image](https://github.com/user-attachments/assets/d8f2a7a0-3865-4856-86cd-5adca1c038d4)

![image](https://github.com/user-attachments/assets/2cc01d91-ac63-45dc-9bed-e4c2f0254d78)

![image](https://github.com/user-attachments/assets/bd770457-d713-4906-9c70-2df7f7af7507)

**Comment by seth-rah** [comment]
That was not the label I was planning to add 😅

**Comment by KevinPayravi** [comment]
Hi @seth-rah! That's a relatively new feature introduced in late April / early May. Indie Wiki Buddy will move indie wikis above Fandom results, and if the indie and Fandom results have the same article name, the Fandom result is hidden.

This feature can be disabled in the extension's settings by un-checking ""Move indie wikis above non-indie results and hide duplicates" in the "Search engine filtering" section. Unfortunately this setting is currently all-or-nothing and cannot be toggled on a per-wiki basis.

**Comment by seth-rah** [comment]
Gotcha

Thanks for the input

I think there would be value in being able to adjust it, but feel free to close this if it's not within the current roadmap :)

**Comment by KevinPayravi** [comment]
I'll close this issue and have opened a new issue to track this feature request: https://github.com/KevinPayravi/indie-wiki-buddy/issues/825

Thank you!
