### ISSUE TITLE
Add a wiki: One piece Wiki

### ISSUE THREAD

**Issue by tachyon2901** [KevinPayravi/indie-wiki-buddy#828]
Link to origin wiki: https://onepiece.fandom.com/wiki/One_Piece_Wiki
Link to destination (independent) wiki: https://breezewiki.com/onepiece/wiki/One_Piece_Wiki

**Comment by DrWhoFan13** [comment]
Breezewiki's a Fandom front-end. All content displayed on it is from Fandom, and all the site does is allow you to view said content without bloat that comes from Fandom.

**Comment by tachyon2901** [comment]
Ahh gotcha that makes sense - is this project specifically meant for indie wiki redirects rather than masks on fandom wikis?

**Comment by KevinPayravi** [comment]
@tachyon2901 Indie Wiki Buddy supports both. We redirect Fandom wikis to their independent counterparts, when they exist. We also have a BreezeWiki function that you can enable to view all English Fandom wikis through BreezeWiki.

**Comment by KevinPayravi** [comment]
Going to close this issue, but please feel free to comment if you have any more questions or if we can clarify anything!

**Comment by tachyon2901** [comment]
my bad @KevinPayravi thanks for clarifying! Really appreciate this extension
