### ISSUE TITLE
Add a wiki: Hello Neighbor Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#832]
Link to origin wiki: https://hello-neighbor.fandom.com/wiki/Hello_Neighbor_Wiki
Link to destination (independent) wiki: https://helloneighbor.wiki.gg/wiki/Hello_Neighbor_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
