### ISSUE TITLE
Add a wiki: Scrabdackle Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#833]
Link to origin wiki: https://scrabdackle.fandom.com/wiki/Scrabdackle_Wiki
Link to destination (independent) wiki: https://scrabdackle.wiki.gg/wiki/Scrabdackle_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
