### ISSUE TITLE
Add a wiki: Aground

### ISSUE THREAD

**Issue by bananstache** [KevinPayravi/indie-wiki-buddy#835]
Link to origin wiki: https://aground.fandom.com/wiki/Aground_Wiki
Link to destination (independent) wiki: https://aground.wiki.gg/wiki/Aground_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
