### ISSUE TITLE
Add a wiki: Super Lesbian Animal RPG Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#836]
Link to origin wiki: https://slarpg.fandom.com/wiki/Super_Lesbian_Animal_RPG_Wiki
Link to destination (independent) wiki: https://slarpg.wiki.gg/wiki/Super_Lesbian_Animal_RPG_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
