### ISSUE TITLE
Add a wiki: Voices of the Void Wiki

### ISSUE THREAD

**Issue by NezcalSpindrake** [KevinPayravi/indie-wiki-buddy#837]
Link to origin wiki: https://votv.fandom.com/wiki/Voices_of_the_Void
Link to destination (independent) wiki: https://voicesofthevoid.wiki.gg/wiki/Voices_of_the_Void_Wiki

**Comment by Steve0Greatness** [comment]
Hey there! I'm not the most knowledgeable in EternityDev and VOTV, but that wiki appears to be for the developer EternityDev, not the game VOTV.

If the EternityDev Fandom wiki were added to Indie Wiki Buddy, it would likely redirect to https://eternitydev.wiki.gg/ instead.

**Comment by NezcalSpindrake** [comment]
Aha! Was not aware EternityDev had a wiki.gg for the whole of it all. Yes that's where it should go then!

**Comment by ToxicPea** [comment]
There also a fandom wiki just for Voices of the Void at https://votv.fandom.com/wiki/Voices_of_the_Void
That's the one that should be redirected to https://voicesofthevoid.wiki.gg/wiki/Voices_of_the_Void_Wiki

**Comment by Steve0Greatness** [comment]
Please separate these into different issues.

**Comment by NezcalSpindrake** [comment]
Edited here, made new issue for EternityDev wiki
