### ISSUE TITLE
Add a wiki: A Hat in Time Wiki / Hattipedia

### ISSUE THREAD

**Issue by ArspenStuffs** [KevinPayravi/indie-wiki-buddy#839]
Link to origin wiki: https://ahatintime.fandom.com/wiki/A_Hat_in_Time_Wiki
Link to destination (independent) wiki: https://ahatintime.wiki.gg/wiki/A_Hat_in_Time_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
