### ISSUE TITLE
Add a wiki: Lexington & Concord Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#847]
Link to origin wiki: https://lexington-and-concord.fandom.com/wiki/Lexington_%26_Concord_Wiki
Link to destination (independent) wiki: https://lexingtonandconcord.miraheze.org/wiki/Main_Page

**Comment by KevinPayravi** [comment]
Thanks for the submission! Will be in the `v3.11.1` release, pending approval from Chrome and Firefox.
