### ISSUE TITLE
Add a wiki: ATLYSS Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#848]
Link to origin wiki: https://atlyss.fandom.com/wiki/Atlyss_Wiki
Link to destination (independent) wiki: https://atlyss.wiki.gg/wiki/ATLYSS_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
