### ISSUE TITLE
Add a wiki: Vectorio Wiki

### ISSUE THREAD

**Issue by Com2486** [KevinPayravi/indie-wiki-buddy#851]
Hello! My name is Com and I am one of the main wiki editors for Vectorio. The fandom wiki was made for an outdated version and was unofficial. The new wiki is official and based off of an independent wiki that I hosted with up-to-date information.
Link to origin wiki: https://vectorio.fandom.com
Link to destination (independent) wiki: https://vectorio.wiki.gg

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
