### ISSUE TITLE
Add a wiki: The Matchless Kungfu Official Wiki

### ISSUE THREAD

**Issue by YewYew** [KevinPayravi/indie-wiki-buddy#852]
**Link to origin wiki:** `https://the-matchless-kungfu.fandom.com/wiki/The_Matchless_Kungfu_Wiki`
**Link to destination (independent) wiki:** `https://thematchlesskungfu.wiki.gg/wiki/The_Matchless_Kungfu_Wiki`

**Comment by KevinPayravi** [comment]
Thanks for the submission! Will be in the `v3.11.1` release, pending approval from Chrome and Firefox.
