### ISSUE TITLE
Add a wiki: Wesley's Roguelike Dungeons mod Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#853]
Link to origin wiki: https://wrdminecraft.fandom.com/wiki/Wesley%27s_Roguelike_Dungeons_mod_Wiki
Link to destination (independent) wiki: https://wesleysroguelikedungeons.wiki.gg/wiki/Wesley%27s_Roguelike_Dungeons_mod_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
