### ISSUE TITLE
Add a wiki: Battle Cats Wiki

### ISSUE THREAD

**Issue by Gideon9212** [KevinPayravi/indie-wiki-buddy#854]
Link to origin wiki: https://battle-cats.fandom.com/wiki/Battle_Cats_Wiki
Link to destination (independent) wiki: https://battlecats.miraheze.org/wiki/Battle_Cats_Wiki

Reason: Fandom wiki is no longer being maintained by it's creator's.

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
