### ISSUE TITLE
Add a wiki: Assault Android Cactus Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#855]
Link to origin wiki: https://assault-android-cactus.fandom.com/wiki/Assault_Android_Cactus_Wiki
Link to destination (independent) wiki: https://assaultandroidcactus.miraheze.org/wiki/Main_Page

**Comment by KevinPayravi** [comment]
Thank you for the submission! The wiki has been added in `v3.11.0` (available for Chrome, soon to be available on Firefox).
