### ISSUE TITLE
Add a wiki: League of Legends

### ISSUE THREAD

**Issue by EssJayEl** [KevinPayravi/indie-wiki-buddy#860]
Link to origin wiki: https://leagueoflegends.fandom.com/wiki/League_of_Legends_Wiki
Link to destination (independent) wiki: https://wiki.leagueoflegends.com/en-us/

**Comment by KevinPayravi** [comment]
Wiki has been committed, will push a release today!

**Comment by KevinPayravi** [comment]
Added in `v3.11.0`
