### ISSUE TITLE
Add a wiki: NixOS Wiki

### ISSUE THREAD

**Issue by Hasnep** [KevinPayravi/indie-wiki-buddy#865]
Link to origin wiki: https://nixos.wiki/
Link to destination (independent) wiki: https://wiki.nixos.org/

**Comment by KevinPayravi** [comment]
Thanks for the submission @Hasnep. Please see this past PR: https://github.com/KevinPayravi/indie-wiki-buddy/pull/672

> I don't currently plan to redirect between independent wikis, even if it is from an unofficial to an official one. A big reason is scope, but also because it requires adding a new permission for the origin domain. Requesting new permissions is a bit disruptive for users as it requires them to approve the new permissions, which isn't really worth it for supporting specific one-offs.

**Comment by Hasnep** [comment]
Oops, sorry! I searched for previous issues but not PRs, thanks for letting me know and thanks for the extension :)
