### ISSUE TITLE
Add a wiki: East Scarp Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#867]
Link to origin wiki: https://eastscarp.fandom.com/wiki/East_Scarp_Wiki
Link to destination (independent) wiki: https://eastscarp.wiki.gg/wiki/East_Scarp_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Will be in the `v3.11.1` release, pending approval from Chrome and Firefox.
