### ISSUE TITLE
Add a wiki: AIBO Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#870]
Link to origin wiki: https://aibo.fandom.com/wiki/AIBO_Wiki
Link to destination (independent) wiki: https://aibo.miraheze.org/wiki/Main_Page

**Comment by KevinPayravi** [comment]
Thanks for the submission! Will be in the `v3.11.1` release, pending approval from Chrome and Firefox.
