### ISSUE TITLE
Add a wiki: Library Of Ruina wiki

### ISSUE THREAD

**Issue by Wiwitorek** [KevinPayravi/indie-wiki-buddy#872]
Link to origin wiki: https://library-of-ruina.fandom.com/wiki/Library_Of_Ruina_Wiki
Link to destination (independent) wiki: https://libraryofruina.wiki.gg/wiki/Library_of_Ruina_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Will be in the `v3.11.1` release, pending approval from Chrome and Firefox.
