### ISSUE TITLE
Add a wiki: Italian and Dutch Minecraft Wikis

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#873]
Link to origin wiki: https://minecraft.fandom.com/it/wiki/Minecraft_Wiki
Link to destination (independent) wiki: https://it.minecraft.wiki/

Link to origin wiki: https://minecraft.fandom.com/nl/wiki/Minecraft_Wiki
Link to destination (independent) wiki: https://nl.minecraft.wiki/

**Comment by KevinPayravi** [comment]
Thanks for the submission! Will be in the `v3.11.1` release, pending approval from Chrome and Firefox.
