### ISSUE TITLE
Add a wiki: League of Legends Wiki

### ISSUE THREAD

**Issue by Werewolf-Wu** [KevinPayravi/indie-wiki-buddy#886]
Link to origin wiki: https://leagueoflegends.fandom.com/
Link to destination (independent) wiki: https://wiki.leagueoflegends.com/

**Comment by KevinPayravi** [comment]
Hi @Werewolf-Wu - the League of Legends Wiki was added to IWB in version 3.11.0, available as of October 10 for Chrome and October 15 for Firefox. If you're not seeing it, please make sure IWB is up-to-date.

**Comment by Werewolf-Wu** [comment]
Add a wiki: League of legends Wiki
