### ISSUE TITLE
Add a wiki: Red Flood Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#890]
Link to origin wiki: https://red-flood.fandom.com/wiki/Red_Flood_Mod_Wiki
Link to destination (independent) wiki: https://redflood.wiki.gg/wiki/Red_Flood_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Will be in the `v3.11.1` release, pending approval from Chrome and Firefox.
