### ISSUE TITLE
Add a wiki: 7 Days to Die

### ISSUE THREAD

**Issue by rAise-IV** [KevinPayravi/indie-wiki-buddy#893]
Link to origin wiki: https://7daystodie.fandom.com/wiki/7_Days_to_Die_Wiki
Link to destination (independent) wiki: https://7daystodie.wiki.gg/wiki/7_Days_to_Die_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Will be in the `v3.11.1` release, pending approval from Chrome and Firefox.
