### ISSUE TITLE
Add a wiki: Marvel Superheroes Mod Wiki

### ISSUE THREAD

**Issue by ToxicPea** [KevinPayravi/indie-wiki-buddy#894]
Link to origin wiki: https://marvel-superheroes-mod.fandom.com/wiki/Marvel_Superheroes_Mod_Wiki
Link to destination (independent) wiki: https://marvelsuperheroesmod.wiki.gg/wiki/Marvel_Superheroes_Mod_Wiki

**Comment by KevinPayravi** [comment]
Thanks for the submission! Will be in the `v3.11.1` release, pending approval from Chrome and Firefox.
