### ISSUE TITLE
Add a wiki: Bloons

### ISSUE THREAD

**Issue by vizthex123** [KevinPayravi/indie-wiki-buddy#895]
Link to origin wiki:
https://bloons.fandom.com/wiki/Bloons_Card_Storm

Link to destination (independent) wiki: 
https://www.bloonswiki.com/Bloons_Card_Storm

**Comment by KevinPayravi** [comment]
Thanks for the submission!

I believe it's still premature to add the independent Bloons Wiki (Fandom has 5,500+ articles, indie has 3,000+). See https://github.com/KevinPayravi/indie-wiki-buddy/issues/802

**Comment by vizthex123** [comment]
oh, i didn't know someone else had suggested it lol.

guess i'll contribute what i can. Don't know much about the series though, so i might just help copy pages from fandom or something.
