### ISSUE TITLE
Add a wiki: Cult of the Lamb Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#898]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://cult-of-the-lamb.fandom.com/wiki/Cult_of_the_Lamb_Wiki
Link to destination (independent) wiki: https://cultofthelamb.wiki.gg/wiki/Cult_of_the_Lamb_Wiki

**Comment by MrPie5** [comment]
The Cult of the Lamb wiki on wiki.gg has closed after the developer and community decided to move back to Fandom.

**Comment by KevinPayravi** [comment]
Interesting, not every day you see a wiki move back. Thank you for the update!
