### ISSUE TITLE
Add a wiki: Etrian Odyssey Wiki

### ISSUE THREAD

**Issue by Gautrot** [KevinPayravi/indie-wiki-buddy#915]
Link to origin wiki: https://etrian.fandom.com/wiki/Etrian_Odyssey_Wiki
Link to destination (independent) wiki: https://etrianodyssey.wiki/wiki/Main_Page

**Comment by KevinPayravi** [comment]
Thanks for the submission Gautrot. Etrian Odyssey has not been added as the Fandom wiki has 1,400+ articles, while the independent wiki has 146.
