### ISSUE TITLE
Add a wiki: Epithet Erased Wiki

### ISSUE THREAD

**Issue by Crystalis39** [KevinPayravi/indie-wiki-buddy#949]
Link to origin wiki: https://epithet-erased.fandom.com/wiki/Epithet_Erased_Wiki
Link to destination (independent) wiki: https://epitheterasedwiki.com/wiki/Epithet_Erased_Wiki

**Comment by KevinPayravi** [comment]
Thank you for the submission! We recently got this submission from another user (https://github.com/KevinPayravi/indie-wiki-buddy/issues/925) -- it's been added and will be available in the next update.
