### ISSUE TITLE
Add a wiki: Crypt of the NecroDancer Wiki

### ISSUE THREAD

**Issue by KevinPayravi** [KevinPayravi/indie-wiki-buddy#98]
An anonymous user has submitted a new wiki via our [submission form](https://form.getindie.wiki).

Link to origin wiki: https://crypt-of-the-necrodancer.fandom.com
Link to destination (independent) wiki: https://necrodancer.miraheze.org

**Comment by Elaeagnifolia** [comment]
Destination Wiki has more content pages (168 vs. 419), and the pages I went through looked good with their information coverage. Destination Wiki also has more recent edits, active editors, and content not covered by the Fandom Wiki (e.g. Synchrony, which appears to be their new DLC).

**Comment by KevinPayravi** [comment]
Now available in version `2.2.0`
